### ISSUE TITLE
read_file_multiprocessing() errors on .xpt file.

### ISSUE THREAD

**Issue by glageju** [Roche/pyreadstat#104]
`df, meta = pyreadstat.read_file_multiprocessing(pyreadstat.read_xport, file_path)` errors out.

**Comment by ofajardo** [comment]
Your error report is extremely vague so I am going to close it.

If you wish you can create a new issue but this tine filll in all the information requested including the error message AND the file causing the error. If I cannot reproduce the error on my side I cant fix it.
