### ISSUE TITLE
Writing to a .sav file if row 0 has been deleted from DataFrame

### ISSUE THREAD

**Issue by jttaggart** [Roche/pyreadstat#106]
Please read the README, particularly the known limitations section!

If row 0 is deleted from the DataFrame there is an error when writing to a .sav file. This only occurs with row 0.

I have a workaround (example in attached) where I move row to end, delete and save.

To Reproduce
See attached: pyread.py

File example
See attached: pyread.sav

Expected behavior
I would expect .sav file to be written without dropped row 0.

Setup Information:
Windows 10 64 bit
Python 3.7
pyreadstat 1.0.8
pip
[pyread.zip](https://github.com/Roche/pyreadstat/files/5889337/pyread.zip)

venv

**Comment by ofajardo** [comment]
Thanks for the very clear and reproducible report. I solved it in the dev branch and will become available in the next release. Will close this issue once the next release is out.

**Comment by jttaggart** [comment]
Thank you. And thank you.

**Comment by ofajardo** [comment]
fixed in version 1.0.9
