### ISSUE TITLE
deprecation warning numpy 1.2 when importing data from spss file

### ISSUE THREAD

**Issue by manfred2020** [Roche/pyreadstat#107]
hello, since numpy version 1.2 i get this message when importing data like this:

"data=prs.read_sav('C:\\Datafiles\\data.sav')"

"C:\Users\Username\envs\EnvName\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel."

then the data don't come as dataframe (like always up to now), but as tuple...

(     sex   age  wohnort  volksmusik  hardrock
 0    1.0  50.0      2.0    2.666667  3.666667
 1    1.0  57.0      1.0    1.000000  3.333333
 2    2.0  66.0      3.0    2.000000  4.333333
 3    1.0  50.0      2.0    2.333333  2.666667
 4    1.0  60.0      3.0    2.333333  3.000000
 ..   ...   ...      ...         ...       ...
 289  1.0  24.0      1.0    5.000000  2.000000
 290  2.0  36.0      1.0    2.000000  3.666667
 291  2.0  31.0      1.0    5.000000  4.666667
 292  1.0  37.0      3.0    5.000000  1.000000
 293  1.0  23.0      1.0    4.333333  3.333333
 
 [294 rows x 5 columns],
 <pyreadstat._readstat_parser.metadata_container at 0x20fadf01588>)

**Comment by ofajardo** [comment]
thanks, regarding the deprecation warning, I'll check what to do to get rid of it.

Regarding the tuple, please take a look to the README, pyreadstat always returns a tuple, therefore you need to unpack it:

```
data, metadata =prs.read_sav('C:\Datafiles\data.sav')
```

**Comment by manfred2020** [comment]
ok, thanks! i wasn't aware that i HAVE TO import "data, metadata = ...".
i always did so, because i always wanted the metadata too... but today i just quickly wanted to import a spss file and didn't add "metadata" :-)

**Comment by ofajardo** [comment]
Solved on dev. Will become available on the next release. I will close the ticket once the next release is there.

**Comment by ofajardo** [comment]
fixed in version 1.0.9
