### ISSUE TITLE
.RData and .RDS support?

### ISSUE THREAD

**Issue by jonathon-love** [Roche/pyreadstat#11]
not sure of your scope for this project, but if you wanted to add .RData support, i have the .pyx and pxd's already done for you.

https://github.com/jamovi/jamovi-readstat/tree/master/jamovi

cheers

jonathon

**Comment by jonathon-love** [comment]
yeah, i'm looking forward to feather et al. they've been a few years coming, so i'd kinda given up on them, but i see they still are being developed and are moving forward.

**Comment by ofajardo** [comment]
Just out of curiosity: why does jamovi necessarily needs to read files from the python server side and cannot read somehow with R? Reading R objects from python back to R sound really convoluted (I certainly have no idea of jamovi architecture, so sorry for the naive question)

**Comment by jonathon-love** [comment]
haha, yes, it is convoluted :) the thing is that we're a spreadsheet, so we need to load the data sets into a nicely editable representation. we're also 'state-ful', so we maintain (and automatically update) the spreadsheet in response to changes to the data (formulas recalculate, etc.)

it's much nicer if i can do all this complicated architecture in python, rather than R.
