### ISSUE TITLE
Inversion types in the doc for pyreadstat.pyreadstat.read_file_in_chunks() function

### ISSUE THREAD

**Issue by labenech** [Roche/pyreadstat#113]
I've a small mistake in the documentation, for the pyreadstat.pyreadstat.read_file_in_chunks() function :

parameters types for multiprocess and num_processes are inverted, should be :

multiprocess (bool, optional) – use multiprocessing to read each chunk?
num_processes (integer, optional) – in case multiprocess is true, how many workers/processes to spawn?

regards

**Comment by ofajardo** [comment]
Thanks! solved in dev, corrected docstrings will become available on the next release, I'll update the webpage now
