### ISSUE TITLE
ReadstatError: A provided name is a reserved word

### ISSUE THREAD

**Issue by mrnguyen14** [Roche/pyreadstat#115]
I don't know why this error happen

the command is: 
pyreadstat.write_sav(df, "destination.sav", file_label="test", column_labels=column_labels)

and Jupyter book show:
---------------------------------------------------------------------------
ReadstatError                             Traceback (most recent call last)
<ipython-input-30-fc53029c8b77> in <module>
----> 1 pyreadstat.write_sav(df, "destination.sav", file_label="test", column_labels=column_labels)

pyreadstat\pyreadstat.pyx in pyreadstat.pyreadstat.write_sav()

pyreadstat\_readstat_writer.pyx in pyreadstat._readstat_writer.run_write()

pyreadstat\_readstat_writer.pyx in pyreadstat._readstat_writer.run_write()

pyreadstat\_readstat_parser.pyx in pyreadstat._readstat_parser.check_exit_status()

ReadstatError: A provided name is a reserved word
--------------------------------------------------------------------------------
but everything is OK if  i run example:

import pandas as pd
import pyreadstat

df = pd.DataFrame([[1,2.0,"a"],[3,4.0,"b"]], columns=["v1", "v2", "v3"])
column_labels = ["Variable 1", "Variable 2", "Variable 3"]
pyreadstat.write_sav(df, "destination.sav", file_label="test", column_labels=column_labels)

Pls help me fix this.

**Comment by ofajardo** [comment]
Sounds like one of your column names is a reserved word, you need to change that name. Try name by name to see where the conflict is. 

Here the relevant code checking for reserved names, check if you have any of those:

https://github.com/WizardMac/ReadStat/blob/69f55186ae615a14a3367ad5cd08b7829aa8f308/src/spss/readstat_sav_write.c#L1258-L1264

**Comment by mrnguyen14** [comment]
> 
> 
> Sounds like one of your column names is a reserved word, you need to change that name. Try name by name to see where the conflict is.
> 
> Here the relevant code checking for reserved names, check if you have any of those:
> 
> https://github.com/WizardMac/ReadStat/blob/69f55186ae615a14a3367ad5cd08b7829aa8f308/src/spss/readstat_sav_write.c#L1258-L1264
