### ISSUE TITLE
international chars in file paths on windows

### ISSUE THREAD

**Issue by jonathon-love** [Roche/pyreadstat#12]
just a heads up, i *think* your current code won't work if there's international chars in file paths on windows (but maybe you've handled somewhere i haven't looked).

i had to use the open_handler() to get it to work in jamovi-readstat:

https://github.com/jamovi/jamovi-readstat/blob/master/jamovi/readstat.pyx#L21-L35
https://github.com/jamovi/jamovi-readstat/blob/master/jamovi/readstat.pxd#L386-L410

cheers

**Comment by ofajardo** [comment]
Hi, Yes you are absolutely right, my code fails with paths with international chars. thanks a lot for pointing it out!
I have therefore tried to bring your code to fix this. I am a bit lost here:

```
cdef extern from *:
      """
      void assign_fd(void *io_ctx, int fd) { ((unistd_io_ctx_t*)io_ctx)->fd = fd; }
      """
     void assign_fd(void *io_ctx, int fd)

```
First cython complains about the triple quotes, I don't know why. So I remove them. Then starts compiling, but later it fails because it says that assign_fd is not defined. Indeed I have not been able to find the definition for this anywhere. Where does it come from?
thanks in advance for the help!

**Comment by jonathon-love** [comment]
hahaha, the definition is *in the quotes* :P that's C code

https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#including-verbatim-c-code

your cython needs updating?

jonathon

**Comment by ofajardo** [comment]
Oh I see! That's what I tought when I saw the comment inside the quotes, but cython rejecting it confused me ... Anyway, thanks for the answer?

**Comment by jonathon-love** [comment]
you could commit as me if you liked? i like the idea of being listed a contributor if it's not too much hassle.

**Comment by jonathon-love** [comment]
i think you just go `git commit -m "blah" --author "first last <user@domain.com>"`

if that doesn't work, it's very easy to change the user after you've committed: [stackoverflow](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit)

i'd PR myself, but those steps of building it on windows to check that it works are a bit overwhelming :)

**Comment by jonathon-love** [comment]
for a really clean commit, you go:

`GIT_COMMITTER_NAME="New Name" GIT_COMMITTER_EMAIL="name@email.com" git commit --author="New Name <name@email.com>"`

without the env variables, github displays the "such and such authored" and "such and such committed"

<img width="488" alt="screen shot 2018-12-18 at 09 36 33" src="https://user-images.githubusercontent.com/3240247/50120074-80318100-02a8-11e9-87c2-4668a55051aa.png">

**Comment by jonathon-love** [comment]
yeah, do you know how to use CMake? i don't really :P

i may have bitten off more than i can chew

**Comment by ofajardo** [comment]
Haha ... And I was thinking ... This guy knows everything!
I am afraid I know less than you, but I wouldn't mind learning a bit, so I can try to help. Unfortunately time I can dedicate to this is limited ... but I guess as everyone's else.

**Comment by ofajardo** [comment]
I upgraded to cython 0.29.1 and now I get this error:

```
Error compiling Cython file:
------------------------------------------------------------
...
        cdef int _SH_DENYRD  # Denies read access to a file.
        cdef int _SH_DENYNO

    cdef extern from *:
        ""
        void assign_fd(void *io_ctx, int fd) { ((unistd_io_ctx_t*)io_ctx)->fd = fd; }
                                                             ^
------------------------------------------------------------

pyreadstat\_readstat_parser.pxd:143:45: Syntax error in C variable declaration
 
```

I don't see anything wrong. Any idea? what version of cython are you using?

**Comment by ofajardo** [comment]
I also tried to move that code to a .c and .h files

the .c file:

```c
#include readstat.h
/*Function used for windows to be able to open files in folders with international characters*/
void assign_fd(void *io_ctx, int fd) 
{ 
	((unistd_io_ctx_t*)io_ctx)->fd = fd; 
}
```

the .h file:
``` c
void assign_fd(void *io_ctx, int fd)
``` 

And now the c compiler freaks out spitting tons and tons of errors. 

some at the beginning:

``` 
building 'pyreadstat.pyreadstat' extension
C:\msys64\mingw64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -I.\pyreadstat -Isrc -Isrc\sas -Isrc\spss -Isrc\stata -Ipyreadstat -I. -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -c pyreadstat/pyreadstat.c -o build\temp.win-amd64-3.6\Release\pyreadstat\pyreadstat.o -Ireadstat -DHAVE_ZLIB=1
pyreadstat/pyreadstat.c: In function 'assign_fd':
pyreadstat/pyreadstat.c:702:80: error: storage class specified for parameter '__Pyx_StringTabEntry'
                 const char is_unicode; const char is_str; const char intern; } __Pyx_StringTabEntry;
                                                                                ^~~~~~~~~~~~~~~~~~~~
pyreadstat/pyreadstat.c:721:79: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 static CYTHON_INLINE int __Pyx_is_valid_index(Py_ssize_t i, Py_ssize_t limit) {
                                                                               ^
pyreadstat/pyreadstat.c:740:34: error: storage class specified for parameter '__Pyx_PyObject_AsString'
 static CYTHON_INLINE const char* __Pyx_PyObject_AsString(PyObject*);

```

and some at the end ...
```
In file included from pyreadstat/pyreadstat.c:692:0:
pyreadstat/pyreadstat_c.h:1:6: error: old-style parameter declarations in prototyped function definition
 void assign_fd(void *io_ctx, int fd)
      ^~~~~~~~~
pyreadstat/pyreadstat.c:8740:1: error: expected '{' at end of input
 }
 ^
error: command 'C:\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1

```

Of course a major difference between your setup and mine is that you are compiling with MSVC ... do you think that has anything to do?

**Comment by jonathon-love** [comment]
yeah, i think the compiler difference *has* to be it :/

**Comment by jonathon-love** [comment]
but this is weird, because it's a cython issue:

```
pyreadstat\_readstat_parser.pxd:143:45: Syntax error in C variable declaration
```

**Comment by jonathon-love** [comment]
i'm using cython 0.28.5

**Comment by jonathon-love** [comment]
```
cdef extern from *:
        ""     # <- not enough quotation marks? supposed to be three?
        void assign_fd(void *io_ctx, int fd) { ((unistd_io_ctx_t*)io_ctx)->fd = fd; }
```

**Comment by jonathon-love** [comment]
```
void assign_fd(void *io_ctx, int fd)   // <- needs a semicolon?
```

**Comment by ofajardo** [comment]
Oh yes, it was the triple quote! sorry! (probably I also forgot the semicolon at the end of the function declaration, but the inline is better, so I discard the c and h files). It compiles! hurray!

So, now next error: when running my tests I get (the ReadstatError is my stuff, but basically is exposing an error return code from readstat).

```
ReadstatError: Unable to seek within file
```

Interestingly I also get this if I compile my library for python2.7 (python 3 is always fine) on windows (unix is fine). What could that mean?

**Comment by jonathon-love** [comment]
wait, so the changes we've just made introduced this problem? (!)

**Comment by ofajardo** [comment]
yes, this is new.

**Comment by jonathon-love** [comment]
ah, i'd say we just have to provide the right arguments to `_wsopen()` to allow seeking ... lemme see.

**Comment by jonathon-love** [comment]
ah, because we're using a custom file open method, we need to provide a custom file seek method. so we need to provide a seek_handler

]we need to call `readstat_set_seek_handler()`

**Comment by ofajardo** [comment]
OK ... how should that look like? Do we need to provide their friends as well (close & read)

**Comment by jonathon-love** [comment]
i suspect we don't have to provide close and read (because i don't, and it works just fine :)

looks like this is what we want: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/lseek-lseeki64?view=vs-2017

**Comment by jonathon-love** [comment]
this?

```
void seek_fd(readstat_off_t offset, readstat_io_flags_t whence, void *io_ctx)
{
    int origin;
    if (whence == READSTAT_SEEK_SET)
        origin = SEEK_SET;
    else if (whence == READSTAT_SEEK_CUR)
        origin = SEEK_CUR;
    else
        origin = SEEK_END;
    _lseek(((unistd_io_ctx_t*)io_ctx)->fd, offset, origin);
}
```

**Comment by ofajardo** [comment]
this is how haven does, we need a handle_seek function that looks similar I think. How to use the functions you just pointed to with this:

```
readstat_off_t seek(readstat_off_t offset, readstat_io_flags_t whence, void *io_ctx) {
    std::ios_base::seekdir dir;
    switch(whence) {
    case READSTAT_SEEK_SET: dir = file_.beg; break;
    case READSTAT_SEEK_CUR: dir = file_.cur; break;
    case READSTAT_SEEK_END:
    default:                dir = file_.end; break;
    }

    file_.seekg(offset, dir);
    return file_.tellg(); // returns -1 if failed
  }
```

**Comment by ofajardo** [comment]
yes, it compiled ... but now this:
```
AttributeError: 'str' object has no attribute 'decode'
Exception ignored in: 'pyreadstat._readstat_parser.handle_open'
```

 and then:

```
ReadstatError: Unable to read from file
ReadstatError: The file's timestamp string is invalid

```

so a few things broken ... but it is also true I had to change a few things ... this is getting complicated ... what if I open a new branch so that you can also look at the code? Or what would you suggest?

I was hoping to do a release version yesterday. This feature seems that is going to take some time to get right, I think I will release without this and this one will make to the next one, I hope you are fine with that.

**Comment by jonathon-love** [comment]
yeah, no worries. no need to rush things. but yup, a WIP branch would be good.

jonathon

**Comment by ofajardo** [comment]
Thanks!
BTW: another tough: you don't need that seek function ... So maybe my problems are related to mingw. In that case we could also  wait for MSVC support to be ready. What's your preference? I can also put the new code in a branch for you to take a look and then we decide.

**Comment by jonathon-love** [comment]
> another thought: you don't need that seek function ... So maybe my problems are related to mingw.

i assumed your tests were making use of more features of readstat than my importing? i.e. some usage pattern of yours was triggering a seek, where as my usage never required one?

**Comment by ofajardo** [comment]
No, I was not setting handlers or something that would trigger a seek, I think

**Comment by ofajardo** [comment]
Yes, that's right

**Comment by ofajardo** [comment]
the latest code is here: https://github.com/ofajardo/pyreadstat

**Comment by ofajardo** [comment]
something quick I can test when I get a bit of time is to replace the original Readstat src folder with the one from your fork and then compile with MSVC. If the problem disappears, then we know what's happening ...

**Comment by jonathon-love** [comment]
```
AttributeError: 'str' object has no attribute 'decode'
```

this looks like the `char *` is being marshaled to a `str` when i expect it to be a `bytes` (and `bytes` has the decode method)

ah, it looks like some behaviour has changed recently in cython, this `c_string_type` option (which you can set globally somewhere i think) looks to be the ticket.

```
c_string_type (bytes / str / unicode)
    Globally set the type of an implicit coercion from char* or std::string.
```

oh wait, it's probably just easier to ditch the `.decode('utf-8')` here:

https://github.com/ofajardo/pyreadstat/commit/ffd0d99d79c57b9052fc33c4c35d55cfdf866061#diff-94b2eb034819b06a2ac77029554af482R672

**Comment by ofajardo** [comment]
hey! you are a start! Yes, that solved the problem. Now issues on windows are gone, and I have added an unitest for the international path and it is working good. 
I tried also with python 2.7 and unfortunately the compilation is broken, because this PyUnicode_AsWideCharString was only introduced on python 3.2. But well, I am not too concerned, I am not willing to invest time on supporting python 2.7

Now, the next thing: I tested on linux (RedHat) and the compilation is broken:

```
pyreadstat/_readstat_parser.c:691:19: fatal error: share.h: No such file or dire                                          ctory
 #include <share.h>
                   ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```
Doing a grep:

```
./pyreadstat/_readstat_parser.c:#include <share.h>
./pyreadstat/_readstat_parser.pxd:    cdef extern from "<share.h>":
``` 
in _readstat_parser.pxd that line is inside: IF UNAME_SYSNAME == 'Windows':
however in the c file it seems there is nothing to check if the system is windows or not when doing the include.

**Comment by jonathon-love** [comment]
Oh yup, so put the include inside an IF?

**Comment by ofajardo** [comment]
the include is already inside an IF that's why I don't understand why cython does not translate to an #if in the c code. Shouldn't this be enough?

```
IF UNAME_SYSNAME == 'Windows':

    cdef extern from "Python.h":
        wchar_t* PyUnicode_AsWideCharString(object, Py_ssize_t *)

    cdef extern from "<fcntl.h>":
        int _wsopen(const wchar_t *filename, int oflag, int shflag, int pmode)
        cdef int _O_RDONLY
        cdef int _O_BINARY

    cdef extern from "<share.h>":
        cdef int _SH_DENYRW  # Denies read and write access to a file.
        cdef int _SH_DENYWR  # Denies write access to a file.
        cdef int _SH_DENYRD  # Denies read access to a file.
        cdef int _SH_DENYNO
```

**Comment by jonathon-love** [comment]
> btw, this thing of bytes vs str is because I have these directives on the top of all my scripts:

*chuckles*, you're killing me bro!

> I don't understand why cython does not translate to an #if in the c code. Shouldn't this be enough?

it's because you've commited the `_readstat_parser.c`, you should add that to your .gitignore

it doesn't do an `#IFDEF` it just strips it out (or includes it) completely. so the .c file needs to be generated as part of the build process.

**Comment by ofajardo** [comment]
When I say compilation fails in line x I of course have tested with both taking the .c file generated on windows and generating it again fresh in linux. Same result.

It is recommended as best practice that you distribute the c file, because if the user has a different version of cython then you can get surprises as we have seen ourselves. The c files should be portable.

https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules

**Comment by ofajardo** [comment]
No, sorry, you are absolutely right. I tested again cleaning everything first and then making sure that cython is translating and indeed now that section is not in the .c file at all, everything compiles and tests pass. 
What I don't get is why they suggest you distribute the .c files. Maybe there is a way to make it portable ...

**Comment by ofajardo** [comment]
OK, it seems that this is indeed a cython limitation. One guy came up with [this module](https://github.com/denik/cython-ifdef) in order to do that, but I prefer not to introduce more dependencies.
I did however a little hack that seems to work (commited and pushed). Do you see any pitfall on doing it?
Now the _readstat_parser.c file works no matter if it was generated on windows and then compiled in linux or viceversa. (I am going to take a rest by doing other tasks now and test again later that what I am saying is true. I am a bit dizzy now of jumping from windows to linux back and forth)

Do you see any pitfall on doing it?

What I basically did is in the _readstat_parser.pxd file, move all those conditional cdefs under IF to a separate conditional_includes.h:

```
#include "Python.h"
 
#ifdef _WIN32

	#include <fcntl.h>
	#include <share.h>
	
	void assign_fd(void *io_ctx, int fd) { ((unistd_io_ctx_t*)io_ctx)->fd = fd; }
	
    long seek_fd(readstat_off_t offset, readstat_io_flags_t whence, void *io_ctx)
        {
            int origin;
            if (whence == READSTAT_SEEK_SET)
                origin = SEEK_SET;
            else if (whence == READSTAT_SEEK_CUR)
                origin = SEEK_CUR;
            else
                origin = SEEK_END;
            return _lseek(((unistd_io_ctx_t*)io_ctx)->fd, offset, origin);
        }
		
#else
	
    int _wsopen(const wchar_t *filename, int oflag, int shflag, int pmode){};
    int _O_RDONLY;
    int _O_BINARY;
	int _SH_DENYRW;  
    int _SH_DENYWR; 
    int _SH_DENYRD;
    int _SH_DENYNO;
    void assign_fd(void *io_ctx, int fd);
    long seek_fd(readstat_off_t offset, readstat_io_flags_t whence, void *io_ctx){};
	
#endif

```

then in the _readstat_parser.pxd simply:

```
cdef extern from "conditional_includes.h":
    wchar_t* PyUnicode_AsWideCharString(object, Py_ssize_t *)
    int _wsopen(const wchar_t *filename, int oflag, int shflag, int pmode)
    int _O_RDONLY
    int _O_BINARY
    int _SH_DENYRW  # Denies read and write access to a file.
    int _SH_DENYWR  # Denies write access to a file.
    int _SH_DENYRD  # Denies read access to a file.
    int _SH_DENYNO
    void assign_fd(void *io_ctx, int fd)
    long seek_fd(readstat_off_t offset, readstat_io_flags_t whence, void *io_ctx)
```

and finally a small change in _readstat_parser.pyx:

```
#IF UNAME_SYSNAME == 'Windows':  # custom file opener for windows *sigh*
    if os.name == "nt":
        readstat_set_open_handler(parser, handle_open)
        readstat_set_seek_handler(parser, seek_fd)
```

**Comment by ofajardo** [comment]
well, one side effect will be that now I am always using PyUnicode_AsWideCharString irrespective of if it is windows or not, meaning compilation on python 2.7 will be broken for all systems. As I said I am not too concerned, but I wonder also how they handle this in python 2.7, maybe there is an easy alternative to PyUnicode_AsWideCharString?

**Comment by jonathon-love** [comment]
oh yup, that all looks good.

i was wondering if the seek handler is actually required?

not sure about the python 2 thing ... i *really* don't like python 2, and am super-keen for it to die out :)

but otherwise, this looks to have come together nicely.

jonathon

**Comment by ofajardo** [comment]
OK, I'll try to remove the seek handler to see what happens. I keep you posted.

**Comment by ofajardo** [comment]
Yes, as you said the seek handler is not needed, so I removed it and all tests pass.
I did a few tweeks and it is portable between Linux and Windows. 
I would like to test once more, but I am leaving for vacation, so I will come back to this in January and do the final merge with the trunk. 
In the meantime it would be good to test this fork on a mac. Do you have a mac and could test (clone, run setup.py install, run tests)? Otherwise I will see if I can ask somebody to do it. It should work but I prefer to avoid surprises later.
Do you see anything else to be done?

**Comment by ofajardo** [comment]
(Notes for myself: It is possible to make the version Python 2.7 compatible, however requires quiet some hacks. The resulting version runs only on python 2.7 on linux but not on windows (seg fault) while the patch was designed to work on windows actually. It requires that fresh .c files are generated, will not work with c files generated by cython on python 3. with  Seems unstable, better leave away, but attached the changes in case they are needed in the future. Changes are NOT commited to the fork.) 
[py27compatible.zip](https://github.com/Roche/pyreadstat/files/2702782/py27compatible.zip)

**Comment by jonathon-love** [comment]
yup, i'll give it a go on macos. enjoy your break!

**Comment by jonathon-love** [comment]
not sure if i'm running the tests in the correct way, but i'm getting one error:

```
jonathon$ env/bin/python3 tests/test_basic.py 
package location: /Users/jonathon/Documents/GitHub/pyreadstat/env/lib/python3.5/site-packages/pyreadstat-0.2.1-py3.5-macosx-10.6-intel.egg/pyreadstat/__init__.py
........E..................
======================================================================
ERROR: test_sas7bdat_international (__main__.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_basic.py", line 136, in test_sas7bdat_international
    df, meta = pyreadstat.read_sas7bdat(os.path.join(self.international_data_folder, "sample.sas7bdat"))
  File "pyreadstat\pyreadstat.pyx", line 92, in pyreadstat.pyreadstat.read_sas7bdat
  File "pyreadstat\_readstat_parser.pyx", line 898, in pyreadstat._readstat_parser.run_conversion
  File "pyreadstat\_readstat_parser.pyx", line 749, in pyreadstat._readstat_parser.run_readstat_parser
pyreadstat._readstat_parser.ReadstatError: Unable to open file

----------------------------------------------------------------------
Ran 27 tests in 0.867s

FAILED (errors=1)
```

**Comment by ofajardo** [comment]
Oh no! ... I think you are running the tests correctly. That particular test failing is a new one I introduced in this fork to test a path with international characters. In the test_data folder thete is a subfolder international with funny characters, inside a sas file, thats the one failing. The intetesting thing is that it was OK on windows and linux ...

**Comment by ofajardo** [comment]
OK! added! Could you try again please?

**Comment by jonathon-love** [comment]
all good.

```
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.985s

OK
```

**Comment by ofajardo** [comment]
brilliant! thanks for the collaboration so far, I've really enjoyed it! Merry Xmas and happy new year in case we don't talk before January.

**Comment by jonathon-love** [comment]
likewise!
