### ISSUE TITLE
Is it any file format needed for pyreadstat.read_dta() ?

### ISSUE THREAD

**Issue by hehuanxiang** [Roche/pyreadstat#122]
Hello engineer, I am a new pythoner.
recently, I am using pyreadstat.read_dta to read my data. The data is like this:
![image](https://user-images.githubusercontent.com/48440077/113963684-a0602200-985c-11eb-9928-61cdae98f9c4.png)

![image](https://user-images.githubusercontent.com/48440077/113963695-a81fc680-985c-11eb-84f7-24487d90e2d2.png)

when I read the data, it gets the error
![image](https://user-images.githubusercontent.com/48440077/113963664-93433300-985c-11eb-884c-bcc92a60222e.png)

I really hope that you can help me to get the solution
thank you so much

**Comment by ofajardo** [comment]
hi, 

pyreadstat reads Stata files which extension is .dta. Those files are binary files (download [this](https://github.com/Roche/pyreadstat/blob/master/test_data/basic/sample.dta) and try to open it in an editor if you want to know what I mean). Your file, even if it has the extension .dta is clearly not a binary file but a text file and clearly not a Stata file, therefore it is not supported. 

The good news is that since it is a text file, you don't need any special parser in order to read it, try first with pandas skipping all the rows in the header, something like: 

```
import pandas as pd
pd.read_csv('file.dta', skip_rows=66)
```
or maybe it is a fix width file and you could try with [pd.read_fwf](https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html), or even just read it line by line and extract the information you need. 

If you still have issues, please look for further assistance in some appropriate forum (stackoverflow maybe); since this is clearly not a pyreadstat issue, I am not going to provide further help here.

Good luck!

**Comment by hehuanxiang** [comment]
> hi,
> 
> pyreadstat reads Stata files which extension is .dta. Those files are binary files (download [this](https://github.com/Roche/pyreadstat/blob/master/test_data/basic/sample.dta) and try to open it in an editor if you want to know what I mean). Your file, even if it has the extension .dta is clearly not a binary file but a text file and clearly not a Stata file, therefore it is not supported.
> 
> The good news is that since it is a text file, you don't need any special parser in order to read it, try first with pandas skipping all the rows in the header, something like:
> 
> ```
> import pandas as pd
> pd.read_csv('file.dta', skip_rows=66)
> ```
> 
> or maybe it is a fix width file and you could try with [pd.read_fwf](https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html), or even just read it line by line and extract the information you need.
> 
> If you still have issues, please look for further assistance in some appropriate forum (stackoverflow maybe); since this is clearly not a pyreadstat issue, I am not going to provide further help here.
> 
> Good luck!

so .DTA is not the same as .dta file ?

**Comment by ofajardo** [comment]
file extensions are irrelevant in this context, the important thing is the content of the file. For example, download [this](https://github.com/Roche/pyreadstat/blob/master/test_data/basic/sample.dta) file, which is a true Stata file to your computer and change the extension from .dta to .xlsx (excel). Then give it to pyreadstat to read and you will see it will work just fine. Try to open it with excel and it will fail. 

In the same way, many different programs can write files with .dta or .DTA extensions: Stata, Turbo Pascal, some video games, laboratory equipment, etc (see [this](https://file.org/extension/dta)). 

In your case it looks as a lab machine. There is for example [this parser](https://pypi.org/project/gamry-parser/) here which may work, actually it looks exactly what you are looking for. 

If not, write your own parser, it is not hard and it is an excellent task for somebody starting with Python or programming in general.

**Comment by hehuanxiang** [comment]
> file extensions are irrelevant in this context, the important thing is the content of the file. For example, download [this](https://github.com/Roche/pyreadstat/blob/master/test_data/basic/sample.dta) file, which is a true Stata file to your computer and change the extension from .dta to .xlsx (excel). Then give it to pyreadstat to read and you will see it will work just fine. Try to open it with excel and it will fail.
> 
> In the same way, many different programs can write files with .dta or .DTA extensions: Stata, Turbo Pascal, some video games, laboratory equipment, etc (see [this](https://file.org/extension/dta)).
> 
> In your case it looks as a lab machine. There is for example [this parser](https://pypi.org/project/gamry-parser/) here which may work, actually it looks exactly what you are looking for.
> 
> If not, write your own parser, it is not hard and it is an excellent task for somebody starting with Python or programming in genre
OK OK，thanks for your help, I think I know how to deal with it.thank you very much again.

**Comment by hehuanxiang** [comment]
> file extensions are irrelevant in this context, the important thing is the content of the file. For example, download [this](https://github.com/Roche/pyreadstat/blob/master/test_data/basic/sample.dta) file, which is a true Stata file to your computer and change the extension from .dta to .xlsx (excel). Then give it to pyreadstat to read and you will see it will work just fine. Try to open it with excel and it will fail.
> 
> In the same way, many different programs can write files with .dta or .DTA extensions: Stata, Turbo Pascal, some video games, laboratory equipment, etc (see [this](https://file.org/extension/dta)).
> 
> In your case it looks as a lab machine. There is for example [this parser](https://pypi.org/project/gamry-parser/) here which may work, actually it looks exactly what you are looking for.
> 
> If not, write your own parser, it is not hard and it is an excellent task for somebody starting with Python or programming in general.

OK OK，thanks for your help, I think I know how to deal with it.thank you very much again.
