### ISSUE TITLE
Double Double-Quotes are being stripped

### ISSUE THREAD

**Issue by wdeaibes** [Roche/pyreadstat#126]
When loading a sas7bdat file using:
df, meta = pyreadstat.read_sas7bdat(InDatFile, row_limit=Parm_SASMaxRowLimit, encoding='utf-8', formats_as_category=True, formats_as_ordered_category=True)

one of the columns is a text columns (4001 characters)
the column contains 2 consecutive double-quotes ("")

when the data frame data is echoed back, one of the double-quotes is eliminated

the resulting length of the 4001 char column is 4000 chars.

is there any way to ask pyreadstat.read_sas7bdat not to interpret the data and store is as-is??

Thanks in advance for any guidance or insights.

Wadih

**Comment by ofajardo** [comment]
Could you please provide a sample file?

**Comment by wdeaibes** [comment]
Hi Otto

Thank you for getting back to me so soon.
Attached is a zip file containing SAS data file and some sample code I used to debug and demonstrate the issue.

I am not now sure if the issue is with pyreadstat of with pandas. As, when I read the df using pyreadstat, display on the screen does not show the double double-quotes, but, when saving the df to a csv, I can see the double double-quotes,.

Kindly, have a look and let me know what you think.

Thanks 

Wadih
[COVaxON.py.zip](https://github.com/Roche/pyreadstat/files/6325164/COVaxON.py.zip)

**Comment by ofajardo** [comment]
hi

As you say I see only one quote in pyreadstat, and that seems to be coming from Readstat (the underlying C library). Something strange however is that in SAS I also see only one quote. (see screenshot). That would make me think that everything is correct in pyreadstat and pandas. So my first question is: why do you think there are two quotes? (if that is the way you see it in SAS, what SAS version are you using?) 
The strange thing is that as you said, when you save the dataframe as CSV, then the double quote magically appears. But that is an artifact of using quotes when saving the CSV: you are using quoting all and double quotes as quotation character, therefore it inserts another quote in front of a double quote to mark that it is not the end of a value but a true double quote. Try by using a different quoting character, let's say single quotes and you will see that the double double quotes dissapear and you will get double single quotes instead, try yet a pipe for example and you will see no extra characters coming out.

for example:

```
df.to_csv("quotes.csv", index=False, quotechar="|")

# This produces: 
Type,VarChar,Numeric,HCN
Max,|aaaaaaa, aaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa? Aaaaaaaaaaaaaaaaaaa(aaaaaaaaaaaaaa) aaaaaaaaaaaaaaaaaaaaaa*aaaaaaaaaaaaaaaaaaaaaaaaaaa&aaaaaaaaaaaaaaaaaa$aaaaaaaaaaaaaaaaaaaaaaaaaaaaa% aaaaaaaaaaaaaaaaaaa@ ... 
```

So my conclusion is that there is only one quote there and everything looks correct. 

SAS:

![image](https://user-images.githubusercontent.com/17498727/115058535-a94c9580-9ee5-11eb-8820-544d4e433598.png)

**Comment by wdeaibes** [comment]
Hi again Otto,

Thanks again for your prompt response.

I confirm and agree with your conclusion that pyreastst is working as designed.
The double double-quote is a the side effect of saving to csv with double-quote as field delimiter.
The actual data did not include 2 double-quotes, only a single double-quote!!

I really appreciated your insights and prompt replies.

Regards,

Wadih

**Comment by ofajardo** [comment]
Happy to help
