### ISSUE TITLE
Use column_names_to_labels (dict instead of list) as argument for write_sav

### ISSUE THREAD

**Issue by Ov-ille** [Roche/pyreadstat#127]
Describe the issue

To write an spss file with column labels the write_sav function only accepts a list as input for the column_labels argument. 
This is a problem, because the list has to be the exact same length as the dataframe (columns) and it also needs to be in the correct order.

The other arguments (value labels, value format, value measure) take dicts as input which is much easier, because it's not a problem if they contain not all or non existing variable names or are in a different order.

It would be great if the same approach could be implemented for column labels!

**Comment by ofajardo** [comment]
OK I added that column_labels can be both a list a dict now. It cannot be instead, because that would be a breaking change that would cause the code of the people to stop working, which is not acceptable. It is already done on dev, will close this issue once it is released.

**Comment by ofajardo** [comment]
available in the new version 1.1.1
