### ISSUE TITLE
Feature request: read a randomly selected subsample

### ISSUE THREAD

**Issue by benjello** [Roche/pyreadstat#136]
It would be nice to have the option to read a sample of a user defined number of row randomly selected across 
the whole data file (similar to sample method of a pandas dataframe).

**Comment by ofajardo** [comment]
As described before, the C library does not allow to access random rows, the only option is to read the file to a pandas dataframe (the whole file or in chunks if too large) and use pandas to select the random sample. This can be done easily on the user side. 
As I have not seen further comments on this, closing this for now.
