### ISSUE TITLE
can't be installed, for(int i=0 **" and "use option -std=c99 or -std=

### ISSUE THREAD

**Issue by amrain-py** [Roche/pyreadstat#148]
Tks much.
It can't be installed due to "for(int i=0 *****" and "use option -std=c99 or -std=***". More info as following:

![130d83962d4e7ad6007165b6f3350ba](https://user-images.githubusercontent.com/55876150/138474664-3d6efb91-7b7a-4e4f-b68e-17012d9eabd1.png)

Setup Information:
pip install
 linux 64 bit
Python 3.7
Python Distribution: Anaconda

**Comment by ofajardo** [comment]
As there is no follow up, I assume the issue has been solved.
