### ISSUE TITLE
Written dta file with version=15 not readable in Stata 17 Basic Edition

### ISSUE THREAD

**Issue by eirki** [Roche/pyreadstat#152]
I'm getting the following error when trying to open a file generated by Pyreadstat in Stata 17 BE-Basic Edition:

>  This .dta file format was created by Stata/MP and has more variables than your Stata can handle.

This happens even if the file contains only one variable (and three observations). It does, however, work if the `version` parameter is 14 or less. It seems they had the same problem over at Haven: https://github.com/tidyverse/haven/issues/461

Reproduction:
```python
import pandas as pd
import pyreadstat
df = pd.DataFrame({"a": [1,2,3]})
pyreadstat.write_dta(df, "data/outfile.dta")  # cannot be read in Stata 17 BE
pyreadstat.write_dta(df, "data/outfile.dta",version=15)  # also cannot be read in Stata 17 BE
pyreadstat.write_dta(df, "data/outfile.dta",version=14)   # success!
```
System:

pandas==1.2.4
pyreadstat==1.1.3

OS: Ubuntu 18.04

Stata 17.0 BE-Basic Edition:

**Comment by ofajardo** [comment]
Reported upstream in Readstat.

**Comment by ofajardo** [comment]
according to [this](https://github.com/WizardMac/ReadStat/issues/259) this is the correct behaviour, therefore closing this issue.
