### ISSUE TITLE
Q: How to define missing values (e.g. '-9')

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [Roche/pyreadstat#161]
Sorry for asking here but I couldn't find a discussion forum or any other support channel for that.

I use `pyreadstat` to save `pandas.DataFrame` based data for SPSS.

How can I define missing values for SPSS?
For example in most of the SPSS using researchs teams the value `-9` is standard for a missing value.

Because of that I do `pandas.DataFrame.fillna(-9)` before writing the SPSS file. But SPSS treat that value as a valid one and not as a defined missing.

**Comment by ofajardo** [comment]
use NaNs, or use user defined missing values, please read the [README](https://github.com/Roche/pyreadstat#writing-user-defined-missing-values)
