### ISSUE TITLE
Multidigit values on string variables are corrupted in missing_ranges 

### ISSUE THREAD

**Issue by eirki** [Roche/pyreadstat#163]
**Describe the issue**
Multidigit values on string variables are corrupted in missing_ranges 

**To Reproduce**
```python
import pyreadstat
import pandas as pd

path = "deleteme.sav"
pyreadstat.write_sav(
    df=pd.DataFrame({"my_variable": ["a_string_value", "6", "66"]}),
    dst_path=path,
    missing_ranges={
        "my_variable": [
            {"lo": "6", "hi": "6"},
            {"lo": "66", "hi": "66"},
        ]
    },
)
df, _ = pyreadstat.read_sav(path, user_missing=False)
print(df)
#       my_variable
# 0  a_string_value
# 1             NaN   <- "6" has correctly been recoded to NaN
# 2              66   <- "66" has not
#
_, meta = pyreadstat.read_sav(path, user_missing=True)
print(meta.missing_ranges)
# {'my_variable': [
#   {'lo': '6', 'hi': '6'},  <- everything fine here
#   {'lo': '\x01', 'hi': '\x01'} <- something going on here
# ]}
```

**Setup Information:**
Ubuntu 20.04
pyreadstat==1.1.4
pandas==1.2.4

**Comment by ofajardo** [comment]
actually the issue was on my side. I was encoding the missing value labels to UTF-8 to obtain bytes that C can use, but somehow (and mysteriously) that is unnecessary and actually caused this issue. Now it is solved on dev.

**Comment by eirki** [comment]
We all need a little mystery in our lives! Thanks for fixing the issue, I look forward to the next release.

**Comment by ofajardo** [comment]
> We all need a little mystery in our lives! 


haha, indeed!

**Comment by eirki** [comment]
Sorry to bother you, @ofajardo, but we are running into this issue on our production system now. Would it be possible to release a new version of Pyreadstat, since the issue is fixed on dev?
