### ISSUE TITLE
Error for empty sas dataset in read_file_multiprocessing

### ISSUE THREAD

**Issue by vng510** [Roche/pyreadstat#172]
Hi,

I'm receiving errors for empty dataset.  See below.

The code:
  reader = pyreadstat.read_file_in_chunks(read_function=pyreadstat.read_sas7bdat, file_path=file, chunksize=200000, 
                                                         multiprocess=True, num_processes=cores, dates_as_pandas_datetime=True)
Error:
pyreadstat/pyreadstat.pyx in pyreadstat.pyreadstat.read_file_multiprocessing()

Exception: The number of rows of the file cannot be determined from the file's metadata

When read the empty dataset using read_sas7bdat, there is no issue and the number of rows is identified correctly as 0.

Thanks!

**Comment by vng510** [comment]
To be clear.  This is from the DEV branch.

**Comment by ofajardo** [comment]
This time I cant do anything without a sample file. Please share the problematic file or generate one that reproduces the issue.

**Comment by ofajardo** [comment]
My thinking is that maybe this issue is similar to #109 in that the SAS file was written by a third party application and the number of rows is not registered in the binary file where expected. The other possibility is that the file was created by SAS but in the special case where there are no rows it is registered in a different way as expected. In this last sceneario you should be able to produce a new file you can share with those characteristics.

**Comment by vng510** [comment]
I created an empty dataset using SAS 9.4. For Python, the version is 3.7.10 on AWS Sagemaker.  I have attached the requirements.txt for review.  I think the scenario that should be considered is that read_sas7bdat registered it correctly with no issue so there is something inconsistent here.

[test.zip](https://github.com/Roche/pyreadstat/files/8326093/test.zip)

**Comment by ofajardo** [comment]
thanks for the sample file it really helped to clarify things. The C library is reading the number of rows correctly, it was rather a glitch in my code. Now it is fixed on dev.

**Comment by vng510** [comment]
Thanks again for supporting this package!  I tested it and it looks like it works.

**Comment by ofajardo** [comment]
Wonderful news! Thanks for testing
