### ISSUE TITLE
I have a problem in importing pyreadstat

### ISSUE THREAD

**Issue by AbdulRaqeeb41** [Roche/pyreadstat#173]
I'm working on jupyter note book

I went to the path folder and checked in  Lib\site-packages. But in packages I couldn't find pyreadstat itself.

Setup Information:
I did not install pyreadstat, It came with ANACONDA which I installed yesterday .conda
Platform : windows-64 bit
Python Version : 3.9.7
Python Distribution- Anaconda
Using condaenv

**Comment by AbdulRaqeeb41** [comment]
I just downloaded the package haha, sorry. I'm new to programming

**Comment by ofajardo** [comment]
Pyreadstat doesnt come installed with anaconda (see [here](https://docs.anaconda.com/anaconda/packages/py3.9_win-64/). Please install it using conda. Please check the readme.
