### ISSUE TITLE
Data Mining

### ISSUE THREAD

**Issue by AbdulRaqeeb41** [Roche/pyreadstat#174]
I'm new to programming, I have a data in format of images and there a something named : .DS_store. [https://drive.google.com/drive/folders/1n86kb1mOg_cWUItlW5T6Jz5D_mKPkjTt?usp=sharing](url) These are the data sets I'm working with. My assignment is I should create my own questions and make a project out of it. Any suggestion? like, what kind of questions I can form and what is the procedure to start. What are the functions I'm gonna need, etc.....

**Comment by ofajardo** [comment]
Sorry, but I don't see how this is related to pyreadstat. Furthermore and in general, this is definetly not a topic for an issue, you could use discussions, but again this is not the appropiate forum as it has nothing to do with pyreadstat.
