### ISSUE TITLE
ImportError: DLL load failed with Python3.9 (and Python 3.10)

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [Roche/pyreadstat#179]
# Introduction
The error is known and well described and solved here
https://github.com/Roche/pyreadstat/issues/33

But this solution did not work for me. I am using Windows 10 64bit. There is no anaconda or virtenv or something like this, just pure Python.

## Two Python versions
**But** there are two interpreters in the system Python 3.9 and Python 3.10. The latter was a fault of my admin and uninstallation did not work well. And that brings me to my next problem: I am not the admin. I am only able to modify the users account part of the `PATH` variable.

I can run both Python interpreters via `py -3` (which is 3.9), `py -3.9` and `py -3.10`. But my target version is 3.9.

## My Hope...
...is that I can modify the users `PATH` that way that I can solve the problem without the admin. But currently it does not work.

# The error message
As you can see on that both error messages I got the error with both python versions.

```
    import pyreadstat
  File "C:\Users\buhtzch\AppData\Roaming\Python\Python39\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
ImportError: DLL load failed while importing pyreadstat: Das angegebene Modul wurde nicht gefunden.

```
and
```
import pyreadstat
  File "C:\Users\buhtzch\AppData\Roaming\Python\Python310\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
ImportError: DLL load failed while importing pyreadstat: Das angegebene Modul wurde nicht gefunden.
```

# How I installed
I installed `pyreadstat` (just to be sure) for both versions
```
py -3.9 -m pip install pyreadstat
py -3.10 -m pip install pyreadstat

```

# Location of the DLLs
The `zlib1.dll` and `libiconv-2.dll` is present in
`%USERPROFILE%\AppData\Roaming\Python\Lib\site-packages\pyreadstat`

# Some more details
This folder do exist in my system

`%USERPROFILE%\AppData\Roaming\Python\Python39\site-packages\pyreadstat
`%USERPROFILE%\AppData\Roaming\Python\Python310\site-packages\pyreadstat

# The `PATH`
After the error (in the Python 3.9 shell) the `PATH` is
```
>>> import os
>>> print('\n'.join(os.environ['PATH'].split(';')))
C:\Program Files\Python310\Scripts\
C:\Program Files\Python310\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\GTK3-Runtime Win64\bin
C:\Users\USER\AppData\Local\Microsoft\WindowsApps
C:\Program Files\Python39
C:\Program Files\Python39\Scripts\
C:\Users\USER\AppData\Roaming\Python\Python39
C:\Users\USER\AppData\Roaming\Python\Python39\Scripts
C:\Users\USER\AppData\Roaming\Python\Lib
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages
C:\Users\USER\AppData\Roaming\Python\Lib\site-packages
C:\Users\USER\AppData\Roaming\Python\Lib\site-packages\pyreadstat
```

I still added some of that folders my self to the users account Path-Setting. But it did not help. Of course I restarted the whole system just to be sure.

**Comment by ofajardo** [comment]
Sorry to hear this issue is poping up in pyreadstat, Please also check this [issue](https://github.com/ofajardo/pyreadr/issues/72) which is the same problem.

In summary, ideally the dlls should be in the same folder as the python files, but for some reason the mechanism to achieve that during installation is broken and the dlls go to strange destinations. If you located them, you can try os.add_dll_directory. otherwise you can copy the dlls into the package folder, or download them from the pyreadstat repo into the package folder. 

You could also try installing anaconda/miniconda, you can do that without admin privileges, but apparently the issue may remain

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
No did not work

```
os.add_dll_directory(r'C:\Users\buhtzch\AppData\Roaming\Python\Python39\site-packages\pyreadstat')
os.add_dll_directory(r'C:\Users\buhtzch\AppData\Roaming\Python\Python310\site-packages\pyreadstat')
```

**Comment by ofajardo** [comment]
OK, another thing would be to know what DLLs are exactly missing (since the Windows error is so nice to not tell us exactly which one). As described in #33 could you please download [Dependencies](https://github.com/lucasg/Dependencies), open the pyreadstat pyd file and see which dlls are missing? Maybe there is something else missing and not what we think.

**Comment by ofajardo** [comment]
I just installed vanilla Python 3.9 into my windows machine, just taking all the defaults the installer suggested, then installed pyreadstat with pip, and it was working out of the box, looking at the package folder, it has all dlls. etc (see screenshot, I deleted my username). So I wonder how to even reproduce this issue and why sometimes dlls get installed somewhere else or the system cannot find them even if you tell them where they are. Please do the dependencies thing, maybe that clarifies something, if it says the dlls missing are the ones you know about, try copying them manually to the package folder to see if that fixes it. 

![image](https://user-images.githubusercontent.com/17498727/164502628-cbebea75-e603-4042-b289-3248838511a5.png)

**Comment by ofajardo** [comment]
Btw, how did you install python? I tried both python.org and miniconda and both are working ok for me

**Comment by nonamephysics** [comment]
Hi guys
I've the same problem while install pyreadstat to the server machine from "requirements.txt" file (for my  personal machine, pip instal... working OK)
Simple pip install ... didn't work for server - problem solved with run cmd for installing "...as administrator"

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I think the "admin" is my problem here. Nothing that can be solved from your site. So I close this.

I am not able to run the "Dependencies" software because I am not the admin. My system rules are extremly restricted.

How I installed Python? The admin did.
The problem was that he/she first installed Python 3.10 from Python.org.
But I needed Python 3.9. So after some weeks he/she came back and "removed" Python 3.10 (via its own installer, which is known not working very well) and then installed Python 3.9 from Python.org.

The default settings for the installer are hard to understand. I do not remember which one the admin (de)activated.

Now I have both versions in the system. The uninstall of 3.10 doesn't work perfectly. I can still go into its shell via `py -3.10`.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Great and thanks a lot.
I can confirm that.

```
Microsoft Windows [Version 10.0.19043.1766]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\buhtzch>py -3
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyreadstat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\buhtzch\AppData\Roaming\Python\Python39\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
ImportError: DLL load failed while importing pyreadstat: Das angegebene Modul wurde nicht gefunden.
>>> exit()

C:\Users\buhtzch>py -3 -m pip install --upgrade pyreadstat
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyreadstat in c:\users\buhtzch\appdata\roaming\python\python39\site-packages (1.1.4)
Collecting pyreadstat
  Downloading pyreadstat-1.1.8-cp39-cp39-win_amd64.whl (2.4 MB)
     ---------------------------------------- 2.4/2.4 MB 1.7 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.2.0 in c:\users\buhtzch\appdata\roaming\python\python39\site-packages (from pyreadstat) (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\buhtzch\appdata\roaming\python\python39\site-packages (from pandas>=1.2.0->pyreadstat) (1.22.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\buhtzch\appdata\roaming\python\python39\site-packages (from pandas>=1.2.0->pyreadstat) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\buhtzch\appdata\roaming\python\python39\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\buhtzch\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pyreadstat) (1.16.0)
Installing collected packages: pyreadstat
  Attempting uninstall: pyreadstat
    Found existing installation: pyreadstat 1.1.4
    Uninstalling pyreadstat-1.1.4:
      Successfully uninstalled pyreadstat-1.1.4
Successfully installed pyreadstat-1.1.8

C:\Users\buhtzch>py -3
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyreadstat
>>>
```

**Comment by ofajardo** [comment]
Glad to hear that, thanks a lot for testing and for the feedback!
