### ISSUE TITLE
Add support for simple bytecode (i.e. row) compression in write_sav()

### ISSUE THREAD

**Issue by mnizol** [Roche/pyreadstat#185]
SPSS files support three levels of compression: Uncompressed, compressed (i.e., simple bytecode compression), and zlib compressed (i.e., zsav format).  The SAVE command in SPSS defaults to writing SPSS files using simple bytecode compression; see [here](https://www.ibm.com/docs/en/spss-statistics/28.0.0?topic=save-compressed-uncompressed-zcompressed-subcommands-command).

The write_sav method in pyreadstat has a boolean compress option, which appears to select between uncompressed and zlib compressed output.  There does not appear to be a mechanism to select SPSS's default simple bytecode compression.

However, the underlying readstat library does appear to support all three forms of compression. The [readstat.h](https://github.com/WizardMac/ReadStat/blob/master/src/readstat.h) header file defines the options in the readstat_compress_e enum (see line 55).  And the [readstat_sav_write.c](https://github.com/WizardMac/ReadStat/blob/master/src/spss/readstat_sav_write.c) module has logic to deal with the simple bytecode case (the enum value for that case is "READSTAT_COMPRESS_ROWS").

Can pyreadstat's write_sav method be updated to provide an option to select simple bytecode compression when it calls the underlying writer in readstat?

I am not familiar with the pyreadstat code base, but I suspect this might be accomplished via a call to the [readstat_writer_set_compression](https://github.com/Roche/pyreadstat/blob/master/src/readstat_writer.c#L510) method at an appropriate spot in the [run_write](https://github.com/Roche/pyreadstat/blob/master/pyreadstat/_readstat_writer.pyx#L670) method and adding a corresponding optional parameter to the run_write method that write_sav can use.

**Comment by ofajardo** [comment]
Thanks for the description and digging into the Readstat code, that helps a lot. Yes, (theoretically) it should be as you say, so I will try it and if it works, then I will include it.

**Comment by ofajardo** [comment]
OK, it is ready on dev, so you can try it if you like. Here a file produced with such compression in case you want to inspect it.
[rowcompression_write.sav.zip](https://github.com/Roche/pyreadstat/files/8642029/rowcompression_write.sav.zip)

**Comment by ofajardo** [comment]
solved in 1.1.6

**Comment by mnizol** [comment]
Thank you!  I've tested the enhancement and it works as expected.  I appreciate your help!
