### ISSUE TITLE
Improve SAS7BDAT reader performance

### ISSUE THREAD

**Issue by jonashaag** [Roche/pyreadstat#193]
I have worked on improving Pandas' SAS7BDAT reader performance in past couple of days. `pyreadstat` was a great source of reference to fix some bugs, thanks a lot for making this project!

I realized that the Pandas reader is much faster at least for the type of files I'm using.

As an example, for a large file with a bunch of millions of rows, `pyreadstat` takes around 20 s to read (both in chunked and non-chunked mode), while the upstream Pandas parser takes around 1 s and my optimized parser (at https://github.com/jonashaag/pandas/tree/fast-sas7bdat-2) takes around 50 ms.

It looks like the bulk of the time is spent in RLE decompression and scanning pages.

Unfortunately I can't share the file but maybe someone else has a publishable example file.

**Comment by jonashaag** [comment]
You are right, I'm going to report this upstream.

**Comment by ofajardo** [comment]
As I cannot action anything here until eventually there are some changes in Readstat, I am going to close this for now.
