### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by behnazelhaminia** [Roche/pyreadstat#194]
Thank you for your code. How can I cite your work in my thesis?

**Comment by ofajardo** [comment]
You will find now a "Cite this repository" section in the about section in the main repo page

![image](https://user-images.githubusercontent.com/17498727/171932638-35bc4bf5-2e26-49b6-bd40-12cd57111da9.png)

**Comment by ofajardo** [comment]
Or you could also follow any other recommendation on how to cite a github repo for example https://www.wikihow.com/Cite-a-GitHub-Repository
