### ISSUE TITLE
Suggestion: in the documentation of `write_` functions correct the file types in `df` and `dst_path` parameters

### ISSUE THREAD

**Issue by remlapmot** [Roche/pyreadstat#197]
This is v.minor point.

On reading the docs for the `pyreadstat.pyreadstat.write_*` functions (e.g., [here](https://ofajardo.github.io/pyreadstat_documentation/_build/html/index.html#pyreadstat.pyreadstat.write_dta)) I noticed that the documentation of the `df` and `dst_path` parameters says for all functions

> ... sav or zsav

whereas it should say the relevant file format for each function, i.e., `write_dta()` should say dta etc (I guess this was a copy-paste error).

**Comment by ofajardo** [comment]
Thanks! I'll correct it.

**Comment by ofajardo** [comment]
corrected!

**Comment by remlapmot** [comment]
Thanks indeed
