### ISSUE TITLE
Import Error on Mac (Apple M1 Pro): (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')

### ISSUE THREAD

**Issue by merjekrepo** [Roche/pyreadstat#199]
I have Mac and get the following error after trying to compile:

`ImportError: dlopen(/Users/fatihshen/Documents/magicstat_venv/lib/python3.10/site-packages/pyreadstat/pyreadstat.cpython-310-darwin.so, 0x0002): tried: '/Users/fatihshen/Documents/magicstat_venv/lib/python3.10/site-packages/pyreadstat/pyreadstat.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/pyreadstat.cpython-310-darwin.so' (no such file)`

My Mac environment:
MacOS Monterey
Version 12.2
Apple M1 Pro

That doesn't give any error on my Windows environment.

I am using PyCharm, with the Python version 3.9.5 in a virtual environment. I run "`pip install pyreadstat`" command on the terminal to install this package.

My guess is that there should be a pyreadstat version specifically built for M1 chip.

Is this a bug or am I missing something? Any ideas how I can overcome this issue?

**Comment by ofajardo** [comment]
There are currently no wheels for M1 on pypi, please install with conda.

**Comment by merjekrepo** [comment]
> There are currently no wheels for M1 on pypi, please install with conda.

I understand. Hope there will be one for pypi in near future bc I don't use conda. Thanks.

**Comment by ofajardo** [comment]
I have uploaded wheels for M1 on pypi. If you test them, please provide feedback.

**Comment by merjekrepo** [comment]
Yes, it is working @ofajardo

This is really fantastic. 

I had to uninstall pyreadstat and reinstall it. Then it worked.

Thanks a lot.

**Comment by ofajardo** [comment]
Great! Thanks for the feedback!

**Comment by henrytdsimmons** [comment]
Thank you so much, this had been causing me a headache!

**Comment by ofajardo** [comment]
great! thanks for the nice feedback!
