### ISSUE TITLE
read_xport number_rows issue with metadataonly

### ISSUE THREAD

**Issue by vng510** [Roche/pyreadstat#208]
Hi!  metadata_container.number_rows return NoneType when read_xport(metadataonly=True).  When metadataonly is False, then it works fine.

**Comment by ofajardo** [comment]
That is the correct behavior and is described in the documentation. It cannot be fixed.

**Comment by vng510** [comment]
Thanks.  This is also probably why read_file_in_chunks wont work with read_xport?

**Comment by ofajardo** [comment]
Correct. Another thing to mention explicitly in the documentation. It was discussed in another issue #105
