### ISSUE TITLE
Sort the dataset

### ISSUE THREAD

**Issue by mehtapuneet151** [Roche/pyreadstat#212]
When I read dataset file in `pyreadstat.read_sas7bdat` we cannot sort the entire dataset. The dataset is getting sorted on the dataframe result got from `pyreadstat.read_sas7bdat` How can we sort the entire dataset?

[Following stackoverflow question](https://stackoverflow.com/questions/74514147/how-to-perform-sorting-using-pyreadstat-library/74533636?noredirect=1#comment131610071_74533636)

**Comment by ofajardo** [comment]
The C backend Readstat does not give the option to sort the data, therefore it cannot be implemented. Please sort the data using pandas sort_values as suggested in Stackoverflow.
