### ISSUE TITLE
read_sas7bdat()  throwing - "Invalid file, or file has unsupported features"

### ISSUE THREAD

**Issue by shivam-agarwal4** [Roche/pyreadstat#214]
### Describe the issue
A very specific error of - "Invalid file, or file has unsupported features" is getting thrown when we are trying to read a sas7bdat file.

Use case - we are reading around 80+ files and are converting it to CSV format files. During the conversion one of the files is failing the conversion and the above mentioned error is thrown. We did try to validate the data in the SAS7BDAT files using SAS viewer but no visible difference was observed in the files from the days it was getting processed. 

When tried using the SAS7BDAT library to read the file and convert it into dataframe, we were able to successfully convert the file that was failing for pyreadstat.read_sas7bdat() function. 

Is this a know issue ? 

### To Reproduce
Python code 
`df, meta = pyreadstat.read_sas7bdat('test.sas7bdat') `

### File example
Since the file has confidential information, it wont be possible to share the original file. Will try to share a mock file if possible

### Expected behavior
The files are getting converted properly without any error

### Setup Information:
How did you install pyreadstat? 
- pip install pyreadstat
Platform
- Windows and Linux
Python Version
- 3.9
Python Distribution 
- System
Using Virtualenv or condaenv? 
- No

**Comment by ofajardo** [comment]
This is an error that comes from the C library Readstat and it means the library cannot parse the file. Why? Impossible to say without inspecting in deep a sample file. The same error can arise from very different files, so just a description of the issue doesn't help. 
You can see similar issues in Readstat, for example https://github.com/WizardMac/ReadStat/issues/287 
I am going to close this as right now there is no action possible without a sample file. If later you can share a file I can reopen or you can open an issue directly in Readstat. 
Notice that issues in Readstat take sometimes long to be solved.
