### ISSUE TITLE
Corrdinate with ReadStat to fix error on bad timestamps in .sav files

### ISSUE THREAD

**Issue by buhrmann** [Roche/pyreadstat#216]
Hi, this is only to ask how difficult it would be, or if you have already planned, to cut a new release that would include [this fix in ReadStat](https://github.com/WizardMac/ReadStat/pull/277)? It seems to be a common occurrence that one cannot read .sav files because of invalid timestamps (e.g. in files from the CIS in Spain), and this would fix that.

**Comment by ofajardo** [comment]
They are doing a lot of fixes these days in Readstat and they are also planning to do a release soon. So, I will do a release immediately after them to capture all the recent changes.

**Comment by buhrmann** [comment]
Ok, I'll keep my eyes open then. You haven't heard anything about a possible time frame for a new release by any chance, no?

**Comment by ofajardo** [comment]
Pyreadstat version 1.2.1 released with Readstat source code updated to version 1.1.9

**Comment by buhrmann** [comment]
That's great, thanks so much!
