### ISSUE TITLE
ReadstatError: Unable to convert string to the requested encoding (invalid byte sequence)

### ISSUE THREAD

**Issue by cfsandford** [Roche/pyreadstat#225]
Describe the issue

pyreadstat is raising a `ReadstatError` while trying to read an spss file.

To Reproduce
Using pyreadstat==1.1.3: Doing `df = pd.read_spss("/path/to/file.sav")` causes this exception to be raised: `ReadstatError: Unable to convert string to the requested encoding (invalid byte sequence)`.

File example
You can get the file here: https://osf.io/6b7fx/download

Expected behavior
I thought that I would be able to read the spss file and get a pandas dataframe back.

**Comment by ofajardo** [comment]
do this:

```
df, meta = pyreadstat.read_sav('PRRI-Brookings 2016 Immigration Survey.SAV', encoding='utf-8')
```
