### ISSUE TITLE
Truncated variable labels when reading Stata .dta files

### ISSUE THREAD

**Issue by chappiewuzefan** [Roche/pyreadstat#227]
**Describe the issue**
When reading Stata .dta files using `pyreadstat.read_dta`, the variable labels are truncated, and I would like to access the full variable labels without truncation.

**To Reproduce**
Here's a code snippet to reproduce the issue:
```
import pandas as pd
import pyreadstat

# Read the Stata .dta file
data_file_path = '33.dta'
df, metadata = pyreadstat.read_dta(data_file_path)

# Access the variable labels
variable_labels = metadata.column_labels

# Create a new DataFrame containing the variable names and labels
var_labels_df = pd.DataFrame({'Variable': df.columns, 'Label': variable_labels})

# Save the DataFrame to a CSV file
output_file_path = 'variable_labels.csv'
var_labels_df.to_csv(output_file_path, index=False)
```

File example
Unfortunately, I cannot share the specific .dta file due to privacy concerns. However, the issue occurs with any .dta file containing variable labels longer than the truncation limit.

Expected behavior
I expect to access the full variable labels without truncation when reading Stata .dta files using pyreadstat.read_dta.

Setup Information:

Installed pyreadstat using pip
Platform: macOS
Python Version: 3.9 
Python Distribution: Anaconda
Not using a virtual environment

**Comment by ofajardo** [comment]
thanks for the file, I can download it and read it in python and see the truncated labels. However, if I read it in stata, I also see that the labels are truncated .... so it looks to me as if python is reading correctly ... can you please elaborate more if this is not accurate?

![image](https://user-images.githubusercontent.com/17498727/236494452-0a5a0c52-f129-4991-be04-97966e2da489.png)

**Comment by ofajardo** [comment]
Opening the file in a binary file editor, also shows that the labels are truncated in the file, that is, there is no more information to be extracted there, see screenshot

![image](https://user-images.githubusercontent.com/17498727/236615836-0afed71f-2199-4a03-a026-d259edeaad8d.png)

**Comment by chappiewuzefan** [comment]
Ohhhh, sorry for that, I should double check it before I issue it. Thanks again for your explaination!!!
