### ISSUE TITLE
pyreadstat.read_sav unable to open SAV file with absolute path

### ISSUE THREAD

**Issue by priya-gitTest** [Roche/pyreadstat#24]
fileT12="H:\\SAV\\SAE.sav"
df, meta = pyreadstat.read_sav(filename_path =fileT12, apply_value_formats=False, dates_as_pandas_datetime=False)
ERROR : 
 File "pyreadstat\pyreadstat.pyx", line 259, in pyreadstat.pyreadstat.read_sav
  File "pyreadstat\_readstat_parser.pyx", line 907, in pyreadstat._readstat_parser.run_conversion
  File "pyreadstat\_readstat_parser.pyx", line 758, in pyreadstat._readstat_parser.run_readstat_parser
pyreadstat._readstat_parser.ReadstatError: Unable to open file

**Comment by ofajardo** [comment]
Please notice that the backslashes are considered escape characters in python. Therefore, on windows, you either precede the string with an r (for raw):

```
fileT12= r"H:\SAV\SAE.sav"
```

or you escape the slashes:

```
fileT12="H:\\SAV\\SAE.sav"
```
Does it solve the issue?

**Comment by priya-gitTest** [comment]
Hi, Actually, pasting the code has removed the other slash, But I do have 2 slashes and it still cannot read the file.

I can use the same path and read the file via the other library but was curios to extract mata data via your library.

**Comment by ofajardo** [comment]
Oh I see in that case I would need your file to take a look at it. Is that
possible?

**Comment by ofajardo** [comment]
Closed because inactivity. 

Reopen if needed, but provide an example file to reproduce the issue.

In case you were using python 2.7, it is not supported on windows. A more clear error us now being provided.

**Comment by tobmcv** [comment]
Hi! I have the same problem with a dataset with the .sav format. It is a timeseries dataset from a national survey.

I managed to convert it in R with the haven package into CSV but I want to do this in Python as well.

[Link to the dataset](https://dfo.no/rapporter-og-statistikk/undersokelser/innbyggerundersokelsen-2019#Se-resultatene-last-ned-rapporten-resultatene-og-sporreskjemaene-fra-innbyggerdelen-av-undersokelsen.:39412)

Download the zip file option. The dataset is 108 MB. I tried using the chunking example and changing the filename but couldn't load it with your package. 

Here is the error from the python console running python 3.8

```
Traceback (most recent call last):
  File "/Users/tobiasmcvey/projects/sav-to-csv/convert.py", line 27, in <module>
    for df, meta in reader:
  File "pyreadstat/pyreadstat.pyx", line 573, in read_file_in_chunks
  File "pyreadstat/pyreadstat.pyx", line 325, in pyreadstat.pyreadstat.read_sav
  File "pyreadstat/_readstat_parser.pyx", line 940, in pyreadstat._readstat_parser.run_conversion
  File "pyreadstat/_readstat_parser.pyx", line 784, in pyreadstat._readstat_parser.run_readstat_parser
  File "pyreadstat/_readstat_parser.pyx", line 714, in pyreadstat._readstat_parser.check_exit_status
pyreadstat._readstat_parser.ReadstatError: Unable to open file
```

I think it might be a metadata issue. 

I tried another sav file and it worked fine. For instance the file in this guide can be read just fine into a pandas dataframe
https://www.marsja.se/how-to-read-write-spss-files-in-python-pandas/

**Comment by ofajardo** [comment]
It works perfectly fine for me, what I did is: 

1- Download the zip file. 
2- Unzip it (pyreadstat does not read zipped files). You get a file "Innbyggerdel tidsserie.sav"
3- Reading the whole file (it's very small) works:

```
>>> import pyreadstat
>>> pyreadstat.__version__
'0.2.9'
>>> df, meta = pyreadstat.read_sav("Innbyggerdel tidsserie.sav")
>>> df.head()
   SPRAAK  Q1_natur_kom_1  Q1_natur_kom_2  Q1_natur_kom_3  Q1_kultur_kom_1  ...  Q58A  Q63A    Q67A  Q53A  Q54A
0     1.0             4.0             3.0             4.0              6.0  ...   NaN   4.0  9999.0   4.0   2.0
1     1.0             7.0             7.0             7.0              6.0  ...   NaN   3.0     1.0   4.0   1.0
2     1.0             5.0             3.0             3.0              6.0  ...   NaN   4.0     2.0   2.0   0.0
3     1.0             7.0             6.0             6.0              6.0  ...   NaN   4.0     1.0   2.0   0.0
4     1.0             6.0             6.0             3.0              3.0  ...   2.0   3.0     1.0   4.0   2.0

```
4- Reading the file in chunks also works:

```
>>> fpath = "Innbyggerdel tidsserie.sav"
>>> reader = pyreadstat.read_file_in_chunks(pyreadstat.read_sav, fpath, chunksize= 10, offset=2, limit=100, disable_date
time_conversion=True)
>>> for df, meta in reader:
...     print(df)
...     break
...
   SPRAAK  Q1_natur_kom_1  Q1_natur_kom_2  Q1_natur_kom_3  Q1_kultur_kom_1  ...  Q58A  Q63A  Q67A  Q53A  Q54A
0     1.0             5.0             3.0             3.0              6.0  ...   NaN   4.0   2.0   2.0   0.0
1     1.0             7.0             6.0             6.0              6.0  ...   NaN   4.0   1.0   2.0   0.0
2     1.0             6.0             6.0             3.0              3.0  ...   2.0   3.0   1.0   4.0   2.0
3     1.0             4.0             7.0             6.0              5.0  ...   2.0   4.0   NaN   5.0   2.0
4     2.0             7.0             7.0             7.0              6.0  ...   1.0   4.0   1.0   2.0   0.0
5     1.0             7.0             7.0             7.0              6.0  ...   2.0   4.0   1.0   3.0   0.0
6     1.0             6.0             2.0             6.0              2.0  ...   1.0   4.0   1.0   4.0   2.0
7     1.0             4.0             6.0             5.0              8.0  ...   NaN   4.0   1.0   NaN   NaN
8     1.0             7.0             7.0             7.0              7.0  ...   2.0   4.0   1.0   4.0   2.0
9     1.0             4.0             4.0             4.0              7.0  ...   NaN   3.0   1.0   2.0   NaN

[10 rows x 266 columns]
```

So I am not sure where the problem is. Have you unziped the file?

**Comment by tobmcv** [comment]
You are right, there is no problem. I thought I needed to escape the space in the file name but I didn't. It works great!

**Comment by ofajardo** [comment]
Great news!

**Comment by antonindanalet** [comment]
I also have problems using read_sav. I use the complete path and escape the backslash ("P:\\…\\… .sav"); there is no white space in the path. The error message is the following:
"File "C:... .py", line 12, in read_data
    df, meta = read_sav("P:\\...\\… .sav")
  File "pyreadstat\pyreadstat.pyx", line 325, in pyreadstat.pyreadstat.read_sav
  File "pyreadstat\_readstat_parser.pyx", line 940, in pyreadstat._readstat_parser.run_conversion
  File "pyreadstat\_readstat_parser.pyx", line 784, in pyreadstat._readstat_parser.run_readstat_parser
  File "pyreadstat\_readstat_parser.pyx", line 714, in pyreadstat._readstat_parser.check_exit_status
pyreadstat._readstat_parser.ReadstatError: Unable to open file"
I am using Python 3.6.1 on Windows 10 with pyreadstat 0.2.9.
Could it be that it is an installation problem with pyreadstat? It is the only reason I can think of. The file can be opened with SPSS.

**Comment by antonindanalet** [comment]
I had the same problem using Windows 10, Python 3.6.1, pyreadstat 0.2.9. After testing, it seems that opening on local drives (e.g., C:) is working, but distant ones are not. In the messages above, the example it with H: and I guess it is the same issue as with my code.

**Comment by ofajardo** [comment]
hmm ... interesting observation. I just tried reading a file on a remote drive and it works fine for me. In my case the remote drive is a samba share ... what kind of remote drive is yours?

**Comment by radhikabhandari** [comment]
Hi, 
I have the same error. 
I installed pyreadstat using pip. Python 3.8.3, pip 20.1.1, conda 4.8.3, Windows 10 
And I am giving absolute path. What might be causing problem?

**Comment by radhikabhandari** [comment]
> Hi,
> I have the same error.
> I installed pyreadstat using pip. Python 3.8.3, pip 20.1.1, conda 4.8.3, Windows 10
> And I am giving absolute path. What might be causing problem?

It worked today itself. Although I do not know what might I caused it.

**Comment by ofajardo** [comment]
@radhikabhandari was the file on a remote drive or local drive?

**Comment by radhikabhandari** [comment]
> @radhikabhandari was the file on a remote drive or local drive?

It was in local drive.
