### ISSUE TITLE
Cannot install the package on python 3.10 or 3.11

### ISSUE THREAD

**Issue by paltusplintus** [Roche/pyreadstat#241]
Please read the README, particularly the known limitations section!

Describe the issue
Cannot install the package on python 3.10 or 3.11 (3.8, 3.9 works fine)
Error message:
```
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zumgjlia/pyreadr_d2efa8aacca44f2b98fb03d2b34e9738/setup.py", line 13, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
```
installing Cython prior to pyreadstat does not help either

To Reproduce
python3.10 -m pip install pyreadstat

File example
```
#FROM python:3.9
FROM python:3.10
#FROM python:3.11
RUN pip install Cython
RUN pip install pyreadstat
RUN /bin/bash
```
Expected behavior
Installation succeeds

Setup Information:
How did you install pyreadstat? : pip
Platform : ubuntu
Python Version: 3.10, 3.11
Python Distribution: python
Using Virtualenv or condaenv?: Virtualenv

**Comment by ofajardo** [comment]
Not sure what is going on, but first observation in case it helps is that you say you are installing pyreadstat, however the error refers to pyreadr which is a different module. So the instructions in your docker file do not match the error.

Second strange thing is that on ubuntu you shoul get a wheel and therefore should not need cython. However I think the python 3.10 image uses debian bookworm, if I am right it may help to use ubuntu (maybe not). Also on what architechture are you working? It should be an exotic one I assume to not find a wheel.

**Comment by ofajardo** [comment]
closed due to lack of activity
