### ISSUE TITLE
Incompatible function parameters: read_file_in_chunks(multiprocess=True, output_format='dict')

### ISSUE THREAD

**Issue by parthkarnawat** [Roche/pyreadstat#251]
Using the read_file_in_chunks method with parameters multiprocess=True and output_format = 'dict' gives the following error:

TypeError: cannot concatenate object of type '<class 'collections.OrderedDict'>'; only Series and DataFrame objs are valid

**Comment by ofajardo** [comment]
Thanks for the report. Fixed in new version 1.2.7
