### ISSUE TITLE
read_dta: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by ankravch** [Roche/pyreadstat#254]
Describe the issue
When reading dta file with unprintable char in label, the following error occurs: "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 66: invalid start byte".

To Reproduce
```
from pyreadstat import read_dta
dd,md=read_dta('bad_char_in_label.dta')
```
File example
https://drive.google.com/file/d/1ncG_Yi29G_yGb0gnlqvgtqiy2dduV87_/view?usp=sharing

Expected behavior
pyreadstat is expected to read dta file with unprintable char in label, as STATA dta reader does

Setup Information:
How did you install pyreadstat?: pip
Platform: linux,  64 bit
Python Version: 3.10.4
Python Distribution: plain python
Using Virtualenv

**Comment by ankravch** [comment]
The issue appears to be resolved by specifying `encoding` option in read_dta function. I tested:
```
dd,md=read_dta('bad_char_in_label.dta', encoding='UTF-8')
dd,md=read_dta('bad_char_in_label.dta', encoding='WINDOWS-1251')
````
both appear to work.

**Comment by tophee** [comment]
@ofajardo I'm struggling with the same error message when reading a dta file but the encoding setting seems to be entirely ignored.

I tried this:
~~~
import pyreadstat
import chardet

with open(datafile,'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']
print(f"File-encoding seems to be {encoding}")

df, meta = pyreadstat.read_dta(datafile, encoding=encoding)
~~~

But it gives me this
~~~
File-encoding seems to be Windows-1254
Traceback (most recent call last):

  Cell In[21], line 12
    df, meta = pyreadstat.read_dta(datafile, encoding=encoding)

  File pyreadstat/pyreadstat.pyx:296 in pyreadstat.pyreadstat.read_dta

  File pyreadstat/_readstat_parser.pyx:1137 in pyreadstat._readstat_parser.run_conversion

  File pyreadstat/_readstat_parser.pyx:769 in pyreadstat._readstat_parser.handle_note

UnicodeDecodeError: byte 0xe4 in position 32: invalid continuation byte
~~~

I also tried various other (guessed) encodings but it always complains that "'utf-8' codec can't decode"

**Comment by ofajardo** [comment]
Try [these](https://gist.github.com/hakre/4188459) one by one (programatically of course)
