### ISSUE TITLE
pyreadstat.write_sav(df, "tmp/data.sav") should raise an error if the directory tmp does not exist.

### ISSUE THREAD

**Issue by h2appy** [Roche/pyreadstat#269]
pyreadstat.write_sav(df, "tmp/data.sav") should raise an error if the directory tmp does not exist.
However, in reality, pyreadstat.write_sav neither saves the file nor provides any exception information.

Please check.
Thanks a lot!

Setup Information:
How did you install pyreadstat? pip
Platform: macOS M1
Python Version: 3.10.11
Python Distribution: plain python
Using Virtualenv or condaenv? python -m venv .venv

**Comment by ofajardo** [comment]
good catch! I raise an error in case the destination folder does not exist.
