### ISSUE TITLE
Support reading from BytesIO object

### ISSUE THREAD

**Issue by pritam-dey3** [Roche/pyreadstat#274]
Feature Request: Support for Reading Files from io.BytesIO in pyreadstat

I would like to request a feature that enables users to read SAS files directly from an io.BytesIO object. Currently, pyreadstat only allows reading files from disk, which poses a limitation in certain scenarios.

For instance:

```python
from io import BytesIO

with open(file_path, 'rb') as file:
    sas_bytes = file.read()  # Read the file as bytes

sas_io = BytesIO(sas_bytes)
df, meta = pyreadstat.read_sas7bdat(sas_io)
```
This feature would be particularly useful in situations like mine, where I am handling SAS7BDAT files within a FastAPI endpoint. Since saving the file temporarily on disk is not permitted, being able to read from a bytes stream would significantly simplify the process.

Setup Information:
How did you install pyreadstat? pip
Windows
Python Version 3.12
Python Distribution Anaconda
Using Virtualenv or condaenv? conda env

**Comment by ofajardo** [comment]
Unfortunately the underlying C library Readstat absolutely needs the file to be on disk, therefore it cannot be fixed. There is a pull request since a few years, but has not being merged. See #8

**Comment by ofajardo** [comment]
@pritam-dey3 .. a bit late, but now this is covered in the new version 1.3.3, via the PR #309 . Big thanks to @slobodan-ilic !

Please check the README for instructions on how to use it.
