### ISSUE TITLE
pyreadstat.__version__ (0.2.3) does not match PyPI version (0.2.5)

### ISSUE THREAD

**Issue by cbrnr** [Roche/pyreadstat#28]
The versions in `pyreadstat.__version__` (0.2.3) and on PyPI (0.2.5) do not match; this makes it difficult to check for a minimum required version.

With the recent changes, do you think you could release 0.2.6 soon? This would be great for our effort to integrate it into pandas.

**Comment by ofajardo** [comment]
definetly, I'll try to get into it soon, but I am quiet busy, hopefully I get it done on next week (I want to introduce some tests for the skip date conversion and take the latest Readtstat release source code as well).

**Comment by ofajardo** [comment]
Fixed. Pyreadstat 0.2.6 is out.
