### ISSUE TITLE
While reading final_model.sav file I am getting error -- The file's timestamp string is invalid

### ISSUE THREAD

**Issue by sohilluhar** [Roche/pyreadstat#32]
Traceback (most recent call last):
  File "read.py", line 3, in <module>
    df, meta = pyreadstat.read_sav('final_model.sav',metadataonly=True)
  File "pyreadstat\pyreadstat.pyx", line 309, in pyreadstat.pyreadstat.read_sav
  File "pyreadstat\_readstat_parser.pyx", line 913, in pyreadstat._readstat_parser.run_conversion
  File "pyreadstat\_readstat_parser.pyx", line 762, in pyreadstat._readstat_parser.run_readstat_parser
pyreadstat._readstat_parser.ReadstatError: The file's timestamp string is invalid

Code:
import pyreadstat

df, meta = pyreadstat.read_sav('final_model.sav',metadataonly=True)

print(df.head())
print(meta.column_names)
print(meta.column_labels)
print(meta.number_rows)
print(meta.number_columns)
print(meta.file_label)
print(meta.file_encoding)

**Comment by ofajardo** [comment]
Please include the problematic file. If I am not able to reproduce the issue I cannot fix it. Include also all relevant information as python version, operating system, spss version, etc.

**Comment by ofajardo** [comment]
Closed due to inactivity.

Feel free to create a new issue comes again, but ONLY if a sample file to reproduce the issue is provided and all other relevant information that is required when filing an issue.
