### ISSUE TITLE
Write SPSS categories

### ISSUE THREAD

**Issue by yvespayette** [Roche/pyreadstat#34]
How to write spss categories?

pyreadstat.pyreadstat.write_sav()

Is there an equivalent spss-like database container type that is free?

Great python module by the way!

**Comment by ofajardo** [comment]
Can you please clarify what is a spss category so that we are on the same page? Please take into account I am not SPSS expert (I have not used it since I was in University).
Right now you won't be able to write those. If it is supported by the C library I will implement in the near future. If not supported by the C library, then I cannot support it either.

**Comment by yvespayette** [comment]
Thank you sir for this fast answer!! Thanks.

Well, SPSS categories are your equivalent of the variable_value_labels  (python dictionary) in the Meta data. If we could write these, as well as missing_user_values, your module would be completely compatible to write SPSS.

However, I am dreaming of a Python type of data container that would do the same and replace either SPSS or SAS data containers. Store variable labels, variable categories, variable missing values, variable type in a single container. I am not sure HDF5 would do the job since viewing HDF does not seem to be widely used and easily done (unlike MySQL, SQLite or other types of storage).

Thanks again! great work that you did!

Yves Payette

________________________________
De : Otto Fajardo <notifications@github.com>
Envoyé : 16 juillet 2019 10:08
À : Roche/pyreadstat <pyreadstat@noreply.github.com>
Cc : yvespayette <yvespayette@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Roche/pyreadstat] Write SPSS categories (#34)


Can you please clarify what is a spss category so that we are on the same page? Please take into account I am not SPSS expert (I have not used it since I was in University).
Right now you won't be able to write those. If it is supported by the C library I will implement in the near future. If not supported by the C library, then I cannot support it either.

**Comment by ofajardo** [comment]
Thanks. If I understand what you are asking for is the writing equivalent of reading value labels and user defined missing values as explained in the README. IF that is correct, yes, I will add support for writing that in the future. 
I definitely align with you that data should be saved in an open and well documented format which in addition can be read from several languages (python, R, java, scala, etc). No idea what is the solution for that, look at Apache Arrow maybe, but that's definitely out of the scope of this project.

**Comment by yvespayette** [comment]
Ok great! Thanks for the tip!

Will be following your work!

________________________________
De : Otto Fajardo <notifications@github.com>
Envoyé : 16 juillet 2019 10:48
À : Roche/pyreadstat <pyreadstat@noreply.github.com>
Cc : yvespayette <yvespayette@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Roche/pyreadstat] Write SPSS categories (#34)


Thanks. If I understand what you are asking for is the writing equivalent of reading value labels and user defined missing values as explained in the README. IF that is correct, yes, I will add support for writing that in the future.
I definitely align with you that data should be saved in an open and well documented format which in addition can be read from several languages (python, R, java, scala, etc). No idea what is the solution for that, look at Apache Arrow maybe, but that's definitely out of the scope of this project.

**Comment by ofajardo** [comment]
The newest release version 0.2.8 has the ability to write user defined missing values and value labels. Let me know if it works for you and feel free to reopen if something is not working.

**Comment by yvespayette** [comment]
Dear Sir!

Wow great news. I am in vacation currently for 3 weeks but will check all this at my return. Since SAS decided to triple their cost, we will graduately switch to Python this year and format our data using your Py module.
This is great, I will give feedback this year and methods to use with Pandas.

Yours,

Yves Payette
Data analyst,
CARTaGENE project
www.cartagene.qc.ca<http://www.cartagene.qc.ca>
Accueil | CARTaGENE<http://www.cartagene.qc.ca/>
Chercheur. Bâtie pour vous. Accédez au portail d'accès et découvrez comment CARTaGENE peut vous aider à accélérer vos recherches en santé.
www.cartagene.qc.ca



________________________________
De : Otto Fajardo <notifications@github.com>
Envoyé : 30 juillet 2019 03:23
À : Roche/pyreadstat <pyreadstat@noreply.github.com>
Cc : yvespayette <yvespayette@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Roche/pyreadstat] Write SPSS categories (#34)


The newest release version 0.2.8 has the ability to write user defined missing values and value labels. Let me know if it works for you and feel free to reopen if something is not working.

**Comment by ofajardo** [comment]
Thanks. Just one question out of curiosity. Is it SPSS or SAS the one rising their prices?

**Comment by yvespayette** [comment]
From what I know, SAS has tripled their price everywhere but SPSS had rise their a couple of years back.
1 licence SPSS = 1000 USD (lifetime) and 1 licence SAS= 2500 USD per year

thanks!



________________________________
De : Otto Fajardo <notifications@github.com>
Envoyé : 30 juillet 2019 17:46
À : Roche/pyreadstat <pyreadstat@noreply.github.com>
Cc : yvespayette <yvespayette@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Roche/pyreadstat] Write SPSS categories (#34)


Thanks. Just one question out of curiosity. Is it SPSS or SAS the one rising their prices?
