### ISSUE TITLE
SPSS: values not being read if value labels are missing

### ISSUE THREAD

**Issue by sayemraza** [Roche/pyreadstat#42]
When I am trying to access meta.variable_value_labels , the values whose value labels are missing are not being read. I am not sure if this is an issue but is there any way I can access those values with value labels as blank?

**Comment by ofajardo** [comment]
Can you please provide an example file with a clear description of what you are getting and what you are expecting to get? Right now I am not sure what you mean and therefore I cannot help.

**Comment by ofajardo** [comment]
Also: check the documentation carefully, specially the section about missing values. Maybe the argument user_missing could help.

**Comment by ofajardo** [comment]
Closed due to lack of reproducibility after several days of inactivity.
