### ISSUE TITLE
Problem Setting Variables width with pyreadstat.write_sav

### ISSUE THREAD

**Issue by Unicorn7GR** [Roche/pyreadstat#46]
Hi there, 

I am trying convert a pd dataframe in to a sav file. Everything works fine (thanx to your package and I'm grateful for that) apart from the dictionary parameters.

I want to save some variables as integers and for them to have missing values as well (NaN)
I know that python does not allow for integers to have NaN values ...but float variables can.
So ...I was thinking of having the variable as float and to remove any decimal points when I convert/save my Dataframe in to a sav file.
_[I'm using Spyder in Anaconda 3 (Python 3.7.3) and the package was installed through conda.]_

So... I have created a **variable_display_width** dictionary with my variables and I was adding the dictionary when I was saving the file....but the file created did not use any of the data set in the dictionary.
I have also tried it with the **variable_measure** which was unknown (I changed it to nominal) but nothing happened again...

On the other hand I tried adding a **column_labels** list and it worked absolutely fine.

Is there something that I need to change when is save the file or is it the package ?

Here is a small example of my syntax. (Let's say that I have a dataframe named **test** that has the following two columns : **Column 1** , **Column 2**)

variable_measure = {"Column 1": "nominal","Column 2": "nominal"}
pyreadstat.write_sav(test, 'C:\\SPSS\\test.sav',variable_measure = variable_measure)

Thank you in advance

**Comment by ofajardo** [comment]
hi

I'm assuming that you are writing the file in python and then willing to open it in SPSS.

What I did is:

* First convert the type of your pandas data frame column to object, so that it can accomodate both integers and floats.
* Cast all non NaN values to integer. 
* Save normally to sav. 

Now when I open it in SPSS I see integer-like values (no decimal place).

Hope it helps.

**Comment by ofajardo** [comment]
just as documentation for myself, or if it is of any interest:

If reading such a file back to python with pyreadstat, the column will be float. That probably is because SPSS saves all numbers as double values. The difference is the number format, if you look at meta.original_variable_types you will see 'F8.0' for this column, the .0 meaning no decimals, while if you save the file as float you will see 'F8.2', .2 meaning two decimals for display. So if one would like to transform the column back to integer, one could again change the column type to object, then cast to integers, the decision wether to do it has to be looking at the decimal places in meta.orginal_variable_types.

**Comment by Unicorn7GR** [comment]
Thank you very much  !!! ...and sorry for the late reply.... (Christmas holidays)

I tried to cast  columns to integer and save it by using the following method.

Converted all columns to **objects** and then tried to convert the ones that I want to integers.
I initially tried int8 then **I**nt8 but python is not converting Objects with NaN to any of these Variable Types. _( **I**nt (Capital **I**) format is the integer format that allows **NaN**s )_
I then converted them to **float** and to **Int8** which worked.
I saved the file as a sav but when I opened the file in SPSS the variables were converted to Strings.

Here is an example of the code I used. _(I am getting my data from a fixed width text file)_

> file_location = "C:\SPSS\data.txt"
> 
> fieldwidths = (3,10 ,10 ,10, 3 ,2,2)
> 
> DataSet = pd.DataFrame(parse_data_file(fieldwidths=fieldwidths, fn=file_location))
> 
> DataSet .columns = ["Column1","Column2","Column3","Column4","Column5","Column6","Column7"]
> 
> Dataset[['Column1','Column5','Column6','Column7']]= Dataset[['Column1','Column5','Column6','Column7']].apply(lambda x: x.replace(r'^\s*$',np.nan,regex=True)) # Putting NaN to empty records
> 
> 
> DataSet=DataSet.astype("object")
> 
> for col in ['Column1','Column5','Column6','Column7']:
>     DataSet[col] = DataSet[col].astype('float64')
> 
> for col in ['Column1','Column5','Column6','Column7']:
>     DataSet[col] = DataSet[col].astype('Int8')
> 
> import pyreadstat
> pyreadstat.write_sav(DataSet,'C:\\SPSS\\DataFile.sav')
> 
> 


Could you please let me know what I am doing wrong ?

**Comment by ofajardo** [comment]
not quiet correct, try something like this (this works for me):

```
import pandas as pd
import numpy as np
import pyreadstat

DataSet = pd.DataFrame([["1"],[""]], columns=["Column1"])

DataSet[['Column1']]= DataSet[['Column1']].apply(lambda x: x.replace(r'^\s*$',np.nan,regex=True)) # Putting NaN to empty records
# Since you are now mixing floats (np.NaN) with strings I think it should be already object, but just in case here again
DataSet=DataSet.astype("object")

# convert to int only the non NaN values, not the whole column! Column should remain as object type
for col in ['Column1']:
    DataSet[~pd.isna(DataSet['Column1'])] = DataSet[~pd.isna(DataSet['Column1'])].astype(np.int)
    
pyreadstat.write_sav(DataSet,'DataFile.sav')
```

**Comment by ofajardo** [comment]
(note for myself). The problem is I was doing:

```
DataSet[['Column1']]= DataSet[['Column1']].astype(np.int8)
``` 

tries to set the data type to np.int8, that effectively raises an error if there is a NaN in the column. 

However doing 

```
DataSet[['Column1']]= DataSet[['Column1']].astype('Int8')
```

Sets the data type to "Int8Dtype" which is pandas type (not numpy) that probably can hold both ints and floats. Therefore I need to incorporate dealing with these Dtypes (there are several) taking into account that they can contain mixed types.

**Comment by ofajardo** [comment]
OK, the problem is solved with commit f1d12a7 (basically your code will work), will be available in the next release.

**Comment by Unicorn7GR** [comment]
Sorry for the late reply and a Big Thank you!

**Comment by ofajardo** [comment]
is it working?

**Comment by priya-gitTest** [comment]
I read a spss file into a dataframe and then write that dataframe into another SPSS file without changing anything and I get this error : module 'pyreadstat' has no attribute 'write_sav'

**Comment by ofajardo** [comment]
most likely you have an old version of pyreadstat, please update and make sure you are using the updated version.

**Comment by jttaggart** [comment]
I have been having the same problem. No labels or values in .sav file.
pyreadstat.write_sav("df.sav", variable_value_labels=meta.variable_value_labels)

**Comment by ofajardo** [comment]
This issue is about the width of the variables not about variable_value_labels. If you have a problem with that please open a new issue and give the complete code to reproduce the issue. If I am not able to reprouce it, I am not able to help.

**Comment by jttaggart** [comment]
Hello,

 

Thank you for fast reply. pyreadstat has made my life so much easier.

 

I updated “var1426” with value labels. When I access “var1426” meta.variable_value_labels all is good. When I save they are missing. All other value_labels are there.

 

df, meta = pyreadstat.read_sav("test.sav", usecols=allList, user_missing=(False))
meta.variable_value_labels.update({"var1426": {"W1": "Wave 1", "W2": "Wave 2", "W3": "Wave 3", "W4": "Wave 4"}})
pyreadstat.write_sav(df, "test_df.sav", column_labels=meta.column_labels, variable_value_labels=meta.variable_value_labels)

 

 

Regards,

 

John

**Comment by ofajardo** [comment]
hi

please open a new issue, and please provide test.sav, otherwise I cannot reproduce the problem

**Comment by jttaggart** [comment]
Hello,

 

I figured it out. If the pyreadstat.write_sav(“file”) exists it doesn’t work.

 

I discovered this by accident when I wrote to a different folder. Solution is to check for and remove file. Also, update of meta.variable_value_labels works perfectly.

 

Obviously I don’t know why this is the case but solution works.

 

Regards,

 

John

**Comment by ofajardo** [comment]
the problem is solved in the new version 0.3.4. Files produced with the old version have to be deleted and produced fresh, otherwise the problem persists.

**Comment by jttaggart** [comment]
Thank you for the update.

**Comment by ofajardo** [comment]
version 1.0.7 has a new argument for write_sav: variable_format which allows to set the format, for example for an integer:

variable_format = {'Column_name':'integer'}

in general the variable format is something like F (float) + variable_width + "." + decimals, for example F8.0 means 8 witdh and 0 decimals (integer), etc.

See more here:

https://github.com/Roche/pyreadstat#setting-variable-formats
