### ISSUE TITLE
read spss file from github

### ISSUE THREAD

**Issue by projectsUW** [Roche/pyreadstat#47]
This is not working:

import pandas as pd
import pyreadstat
pd.read_spss('https://github.com/UWDataScience2020/data/raw/master/hsb_ok.sav')

Is it possible?

**Comment by ofajardo** [comment]
Unfortunately it is not possible. The underlying C library absolutely requires a file on disk, therefore pyreadstat also requires it. I leave to the user to decide how to download the file.

You could do something like this:

```
from urllib.request import urlopen
import pandas as pd
import pyreadstat

link="https://github.com/UWDataScience2020/data/raw/master/hsb_ok.sav"
response = urlopen(link)
content = response.read()
fhandle = open('file.sav', 'wb')
fhandle.write(content)
fhandle.close()
result = pd.read_spss("file.sav")
```
