### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:

### ISSUE THREAD

**Issue by sebanger** [Roche/pyreadstat#48]
Hi,

I would like to install pyreadstat with the following command:
    conda install -c conda-forge pyreadstat

but I get the following error:
PackagesNotFoundError: The following packages are not available from current channels:
- pyreadstat

Current channels:
  - https://conda.anaconda.org/conda-forge/win-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

I am using the following:
Python 3.7.4 
Anaconda3 2019.10
on Win 32

**Comment by ofajardo** [comment]
conda forge does not seem to support 32 bit packages, that's why only 64 bit are there and you are not finding the ones for your architecture. 
Please use pip instead of conda, there are 32 bit wheels there:
```
pip install pyreadstat
```

**Comment by tgtimoteo** [comment]
Hi @ofajardo, Can you help me? I've tried to install this package through conda and, but I can't import it. It's Python 3.7.0 in Windows 10. When I install through pip and run the 'import pyreadstat', I get the message: 'ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.'. 
I also tried the compilaton options from github and didn't work as well.

**Comment by ofajardo** [comment]
Make sure the folder where the dlls are installed is on Windows PATH.
See #33

**Comment by tgtimoteo** [comment]
I had read it, but I did it again and it worked. Thanks.

**Comment by ofajardo** [comment]
I'm assuming this is solved then.

**Comment by sebanger** [comment]
thank you. Yes this is solved.
