### ISSUE TITLE
File written by pyreadstat cannot be removed with os.remove on windows

### ISSUE THREAD

**Issue by ofajardo** [Roche/pyreadstat#49]
On windows, after writing a file (so it's closed), the file looks good and it is possible to delete it from windows file explorer. However if trying to remove from python with os.remove, it raises an error:

```
PermissionError: [WinError 5] Access is denied
```

Permissions on windows again look good, but if looking at the permissions with python like this:

```
oct(os.stat("test.txt")[ST_MODE])[-3:]
```
you get: 444, while in WSL you get -r-xr-xr-x

doing os.chmod(file_path, stat.S_IRWXU) makes it possible to delete it, but should this file be writable/deletable from the beginning?

**Comment by ofajardo** [comment]
hi @jonathon-love! How are you doing? have you seen this behavior before? do you know by chance why this happens and how to solve it?

**Comment by ofajardo** [comment]
Another issue arising from this is that if one tries to overwrite the file with new information (for example update value_variable_labels) python doesn't raise any error at all, but the change in the file doesn't take effect. 

Solution for now would be change file permissions with os for windows to only.

**Comment by jonathon-love** [comment]
oh hey, @ofajardo,

i somehow missed your correspondence on this. sorry, i'm not sure i've seen this before. there are some inconsistencies in python's temp files handling on different OSes, but that doesn't seem to be in play here.

**Comment by ofajardo** [comment]
Hi @jonathon-love 

No problem! Do you think just changing permissions with os is good enough? What permissions would you suggest? Read and write for user and group? For everyone?

Just in case you have not seen it, I filed this issue as well on jamovi Readstat, I have seen these problems when using Jamovi GUI as well.

**Comment by jonathon-love** [comment]
surely we're doing something wrong somewhere. this is what i'm doing:

https://github.com/jamovi/jamovi-readstat/blob/master/jamovi/readstat.pyx#L28-L35

this is where i set the flags for opening the file, surely the problem is here.

**Comment by jonathon-love** [comment]
what's the `_SH_DENYRD` anyway? :P

**Comment by jonathon-love** [comment]
do we just change it to `_SH_DENYNO` and we're done?!

**Comment by ofajardo** [comment]
Nope, unfortunately that didn’t help

**Comment by jonathon-love** [comment]
for real?! that totally seemed like a smoking gun ... it seems to match the symptoms perfectly ...

let me spin up a VM

**Comment by jonathon-love** [comment]
ok ok, what about this?!

`https://github.com/jamovi/jamovi-readstat/commit/8a16645474402d88ce699e67ffabda88a8506467`

i read the documentation a little more this time, and i'm confident *this* is it :P

jonathon

**Comment by ofajardo** [comment]
hmm, still the same for me :(

**Comment by jonathon-love** [comment]
it fixes it for me!

**Comment by ofajardo** [comment]
oh yes, actually it did fix it for me as well, as I was running unittests, I had the file written from before with the wrong permissions, overwriting it doesn't fix it, but after deleting it and creating it fresh, everything looks good now! 
I commited with your name, does it look good to you? https://github.com/Roche/pyreadstat/commit/ba305c8ac6f36c87cda2d535e74eaaae086d1b7f

**Comment by jonathon-love** [comment]
sure! although it does look suspiciously like my code in the first place  :P

glad you're keeping on top of pyreadstat!

cheers

jonathon

**Comment by ofajardo** [comment]
yes, I took the file writing function open_file we are discussing from pyreadr (I have to fix it over there as well), which means taking it from you. The rest of the readstat writer is mine as I wrote it following a procedural style consistent with the readstat reader in opposition to your object-oriented way. 
I hope it was fine to steal those few lines from you!

**Comment by jonathon-love** [comment]
haha, of course! we're all on the same team :)

**Comment by ofajardo** [comment]
as usual a pleasure collaborating with you! Looking forward to the next time!
