### ISSUE TITLE
Cannot set `variable_to_label` when writing .sav file

### ISSUE THREAD

**Issue by RobinJayaswal** [Roche/pyreadstat#50]
## Describe the issue

I wish to set a label on the column names when writing a file. I see that the library has the functionality to read such labels:

```python
df, meta = pyreadstat.read_sav("test_data/basic/sample.sav")
# the variables mylabl and myord are associated to the label sets labels0 and labels1 respectively
print(meta.variable_to_label)
#{'mylabl': 'labels0', 'myord': 'labels1'}
```

But I see no such option when writing.

I would be great if I could pass `variable_to_label` when writing a .sav file, for example:

```
pyreadstat.write_sav(df, str(output_filepath), variable_value_labels=variable_value_labels, variable_to_label={ 'q1': 'This my question!', ...})
```

**Comment by ofajardo** [comment]
As described in the [documentation](https://ofajardo.github.io/pyreadstat_documentation/_build/html/index.html), in the write_sav section, you should use column_labels

```
column_labels (list, optional) – list of labels for columns (variables), must be the same length as the number of columns. Variables with no labels must be represented by None.
```

**Comment by RobinJayaswal** [comment]
Don't know how I missed that in the docs! Thanks!

**Comment by ofajardo** [comment]
No prob! Also, when reading you should be looking at column_labels or column_names_to_labels and not variable_to_label which is a variable for debugging ... See again documentation, at the top, metadata object description
