### ISSUE TITLE
[Request] .whl file for Python version 3.8

### ISSUE THREAD

**Issue by mphilli** [Roche/pyreadstat#51]
Latest upload date for .whl files was Aug 27, 2019, per: [https://pypi.org/project/pyreadstat/#files](https://pypi.org/project/pyreadstat/#files). As of Python's 3.8 Release (Oct 14, 2019), wondering if a "cp38" whl file can be posted. 

Thanks.

**Comment by ofajardo** [comment]
Yep. I am waiting for a new Readstat version which should come very soon. That will trigger a new pyreadstat version. I was waiting for that to introduce the wheels for py38, but if I get a bit if time, I'll do it for the current pyreadstat version already. 
In the meantime you can install with conda, there is py38 there.

**Comment by ofajardo** [comment]
Done. Python 3.8 wheels now available on pypi for the current version.
