### ISSUE TITLE
values to labels. if I remove some column...

### ISSUE THREAD

**Issue by MaxPao** [Roche/pyreadstat#58]
if I use like this code...
df2=df[['id','zip','sex']]
df_enriched = pyreadstat.set_value_labels(df2, meta, formats_as_category=True)

it's can't show edited df with ValueLabels?

thank you very much

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

**Comment by ofajardo** [comment]
done. feature available in the new version 0.3.3
