### ISSUE TITLE
ReadstatError: File has an unsupported character set

### ISSUE THREAD

**Issue by MingHanLee** [Roche/pyreadstat#65]
I'm getting this error when I try to read_sas7bdat on a sas7bdat file:
```
import pyreadstat

df, meta = pyreadstat.read_sas7bdat(filename_path='data.sas7bdat', 
                                    disable_datetime_conversion=False, 
                                    encoding='iso-8859-1',  
                                    metadataonly=False,
                                    user_missing=False)
```

> Traceback (most recent call last):
> 
>   File "<ipython-input-1-f4c1213ae971>", line 1, in <module>
>     runfile('C:/Users/Hank Lee/Anaconda3/Lib/site-packages/conda/common/sas.py', wdir='C:/Users/Hank Lee/Anaconda3/Lib/site-packages/conda/common')
> 
>   File "C:\Users\Hank Lee\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\Hank Lee\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/Hank Lee/Anaconda3/Lib/site-packages/conda/common/sas.py", line 38, in <module>
>     user_missing=False)
> 
>   File "pyreadstat\pyreadstat.pyx", line 109, in pyreadstat.pyreadstat.read_sas7bdat
> 
>   File "pyreadstat\_readstat_parser.pyx", line 945, in pyreadstat._readstat_parser.run_conversion
> 
>   File "pyreadstat\_readstat_parser.pyx", line 784, in pyreadstat._readstat_parser.run_readstat_parser
> 
>   File "pyreadstat\_readstat_parser.pyx", line 714, in pyreadstat._readstat_parser.check_exit_status
> 
> ReadstatError: File has an unsupported character set

### Setup Information:
How did you install pyreadstat? (pip, conda, directly from repo)
conda

pyreadstat version
1.0.0

Platform (windows, macOS, linux, 32 or 64 bit)
windows

Python Version
3.6

Python Distribution (System, plain python, Anaconda)
Anaconda

**Comment by ofajardo** [comment]
The most likely reason is that the encoding you are setting is not correct. Try leaving out the encoding parameter or change the encoding to something else (try different ones). 

If this doesn't improve things, please provide an example file. If I am not able to reproduce the issue I am not able to help.

**Comment by ofajardo** [comment]
Closed due to inactivity and lack of reproducibility.
