### ISSUE TITLE
write_sav: variable_display_width always 0

### ISSUE THREAD

**Issue by josmos** [Roche/pyreadstat#72]
The Parameter for setting the display width is ignored:

```
import pandas as pd
import pyreadstat

df = pd.DataFrame({
    "v1": {
        "10001": """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac pretium sem. Fusce aliquet
        augue rhoncus consequat pulvinar. In est ex, porta congue diam sed, laoreet suscipit purus. Phasellus mollis
        lobortis tellus at vehicula. Etiam egestas augue id massa bibendum volutpat id et ipsum. Praesent ut lorem
        rhoncus, pharetra risus sed, pharetra sem. In pulvinar egestas erat, id condimentum tortor tempus sed. Duis
         ornare lacus ut ligula congue, non convallis urna dignissim. Etiam vehicula turpis sit amet nisi finibus
         laoreet. Duis molestie consequat nulla, non lobortis est tempus sit amet. Quisque elit est,
         congue non commodo vitae, porttitor ac erat. """,
        "10002": "fgsdghshsgh",
        "10003": "gsfdgsdg",
    },
    "v2": {
        "10001": "gsfdgsfdgsfg",
        "10002": "fgsdghshsgh",
        "10003": "gsfdgsdg",
    },

})

pyreadstat.write_sav(df, "export.sav", variable_display_width={"v1": 100})

df, meta = pyreadstat.read_sav("export.sav")
print(meta.variable_display_width)
#{'v1': 0, 'v2': 0}
```

**Comment by ofajardo** [comment]
Thanks for the report. It is the length of the string, if it is less than 256 characters, then variable_display_width is written correctly. If 256 or more then you get 0. 

This looks like coming from the C code (Readstat, so I'll file an issue over there on your behalf)

**Comment by ofajardo** [comment]
Another note: the max variable_display_width should be 40, so 100 wouldn't make sense. 

In old times it seems that the max string was 255, maybe that has something to do with what's happening here, but actually no idea. 

https://www.ibm.com/support/pages/how-many-characters-can-string-or-numeric-variable-take-spss

**Comment by ofajardo** [comment]
Issue in Readstat: https://github.com/WizardMac/ReadStat/issues/210

**Comment by ofajardo** [comment]
Solved on dev, although the max width right now is 255 (should be much larger)

**Comment by ofajardo** [comment]
this is now fully solved!
