### ISSUE TITLE
pyreadstat._readstat_parser.ReadstatError: Unable to convert string to the requested encoding (invalid byte sequence)

### ISSUE THREAD

**Issue by jingyulong** [Roche/pyreadstat#74]
# Describe the issue
I am currently reading the SAV file, but I have encountered a problem with the encoding format of the file and it cannot be read. The file contains Chinese characters, but I tried the GBK format, but it still doesn't work. There were also files with Chinese characters before, but they all worked normally, but this file does not work. Could you help me see what the problem is?
I tried to read the source code, but I don't know how to debug it. I will attach the file later.

# To Reproduce
Python code
``` pyreadstat.read_sav("test1.sav")```

# File example
[test1.zip](https://github.com/Roche/pyreadstat/files/5166934/test1.zip)

# Expected behavior
Can read the file normally, or how to solve the encoding problem

Setup Information:
How did you install pyreadstat? conda
Platform (windows)
Python Version 3.7.6
Python Distribution (Anaconda)
Using Virtualenv or condaenv? condaenv

**Comment by ofajardo** [comment]
regarding the content SPSS thinks indeed all of them are empty strings. Are you sure there is some content in there?

**Comment by jingyulong** [comment]
> error, however the second column is empty. If I understand correctly, there should be some chinese characters there? **Can you please confirm? Can you please declare what is the exact expected output?**

Hi ofajardo, sorry for the late reply. 
The data set of test1 is indeed no problem in reading data after the upgrade version. The previous version was 0.3.3. But I have a large piece of data in my hand, and there is still a problem in reading it, because it is the company's confidential data, so it is difficult for me to separate the problematic test data. I configured the environment over the weekend, but I encountered a problem and there was too little documentation about debugging.
If I have time, I will try again.

**Comment by jingyulong** [comment]
> regarding the content SPSS thinks indeed all of them are empty strings. Are you sure there is some content in there?

These data do not contain content, but encountered problems when reading. Chinese characters are found in meta. The result I expect is just to read the data normally. I will try again and generate a test data for you.

**Comment by ofajardo** [comment]
I do get some chinese characters in meta:

```
>>> import pyreadstat
>>> df, meta = pyreadstat.read_sav("test1.sav")
>>> meta.column_labels
['号码', '请表明被使用得到号码源文件的名字']
```

**Comment by jingyulong** [comment]
I tried to compile this module and then degub locally, but an error was reported during the compilation. I googled for a long time and this problem was not solved.

The environment I use is centos, anaconda, and the error is as follows:
```
./src/spss/readstat_sav_write.c:26:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
error: command '/root/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
```

Please tell me how can I solve this problem? @ofajardo

**Comment by ofajardo** [comment]
You have to install zlib dev.

So far you still have not indicated what is your issue. For me all looks ok with the dataset you shared.

**Comment by jingyulong** [comment]
Hi ofajardo,

I finally found the problematic data, as follows:
[test_data_label_issue.zip](https://github.com/Roche/pyreadstat/files/5205696/test_data_label_issue.zip)

The exact expected output：
Normally read the data. After reading, the label of the variable "Detail" should be: "请提供尽可能多的附加细节"。Notice that there is no value in this variable.
![image](https://user-images.githubusercontent.com/14075628/92851468-2c71ae80-f420-11ea-9213-c3c6f0357117.png)

**Comment by ofajardo** [comment]
I can't reproduce the issue. This is what I get:

```
>>> import pyreadstat
>>> df, meta = pyreadstat.read_sav("test_data_label_issue.sav")
>>> meta.column_labels
['请提供尽可能多的附加细节。']
```

which looks correct to me. What are you getting and how are you getting it?

**Comment by jingyulong** [comment]
> I can't reproduce the issue. This is what I get:
> 
> ```
> >>> import pyreadstat
> >>> df, meta = pyreadstat.read_sav("test_data_label_issue.sav")
> >>> meta.column_labels
> ['请提供尽可能多的附加细节。']
> ```
> 
> which looks correct to me. What are you getting and how are you getting it?

Please try with the encoding GBK：
```
>>> import pyreadstat
>>> df, meta = pyreadstat.read_sav("test_data_label_issue.sav",**encoding="GBK"**)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyreadstat/pyreadstat.pyx", line 325, in pyreadstat.pyreadstat.read_sav
    data_frame, metadata = run_conversion(filename_path, file_format, readstat_parse_sav, encoding, metaonly,
  File "pyreadstat/_readstat_parser.pyx", line 945, in pyreadstat._readstat_parser.run_conversion
    run_readstat_parser(filename, data, parse_func, row_limit, row_offset)    
  File "pyreadstat/_readstat_parser.pyx", line 784, in pyreadstat._readstat_parser.run_readstat_parser
    check_exit_status(error)
  File "pyreadstat/_readstat_parser.pyx", line 714, in pyreadstat._readstat_parser.check_exit_status
    raise ReadstatError(err_message)
pyreadstat._readstat_parser.ReadstatError: Unable to convert string to the requested encoding (invalid byte sequence)
```

**Comment by ofajardo** [comment]
The encoding of the file is UTF-8 and not GBK.

I tested on windows and got this:

```
>>> import pyreadstat
>>> df, meta = pyreadstat.read_sav("test_data_label_issue.sav")
>>> meta.column_labels
# Here a lots of squares with question marks
# however if I just copy paste into here it displays correctly:
# '请提供尽可能多的附加细节。'
```

Is that the problem you are facing?

In addition if you transform that to bytes, and then reconvert to characters on a mac machine it is fine:

```
# windows
meta.column_labels.encode("UTF-8")
b'\xe8\xaf\xb7\xe6\x8f\x90\xe4\xbe\x9b\xe5\xb0\xbd\xe5\x8f\xaf\xe8\x83\xbd\xe5\xa4\x9a\xe7\x9a\x84\xe9\x99\x84\xe5\x8a\xa0\xe7\xbb\x86\xe8\x8a\x82\xe3\x80\x82'
# Mac
>>> a = b'\xe8\xaf\xb7\xe6\x8f\x90\xe4\xbe\x9b\xe5\xb0\xbd\xe5\x8f\xaf\xe8\x83\xbd\xe5\xa4\x9a\xe7\x9a\x84\xe9\x99\x84\xe5\x8a\xa0\xe7\xbb\x86\xe8\x8a\x82\xe3\x80\x82'
>>> a.decode("UTF-8")
'请提供尽可能多的附加细节。'
```

So, that means pyreadstat is handling the encoding correctly, and it is windows, or python on windows which is failing to display it properly. Something along these lines:

https://support.microsoft.com/en-nz/help/3083806/why-does-some-text-display-with-square-boxes-in-some-apps-on-windows-1

Unfortunately there is nothing we can do about it, since it is a windows issue. Please investigate more on the windows side. Try to update to a newer version of python as well.

**Comment by ofajardo** [comment]
extra: copying and pasting this string:

```
'请提供尽可能多的附加细节。'
```

into windows notepad displays correctly. However, copying it into the python console displays the questionmarks. Probably it is some specific issue of python on windows then.

**Comment by ofajardo** [comment]
Oh, in addition doing it using Spyder instead of the naked windows command prompt does give the correct result! It also works well using Visual Studio Code, but not using Windows Power shell.

So, it looks like it is windows - app dependent. Please just use a windows app that does display things correctly, or play with your windows configuration to get it to work. Again, I don't see any issue in pyreadstat.

**Comment by evanmiller** [comment]
I don't know if it helps but you can set the output encoding in ReadStat using:

```C
readstat_error_t readstat_set_handler_character_encoding(readstat_parser_t *parser, const char *encoding);
```

It defaults to UTF-8 but accepts any iconv encoding name.

**Comment by ofajardo** [comment]
@evanmiller thanks for the suggestion.

I am currently using readstat_set_file_character_encoding, according to me for the same purpose. What is the difference?

**Comment by ofajardo** [comment]
oh, is it like the one I am using to set what is the encoding of the input file (that's what I am using it for), and the one you are saying will set the encoding for the data you get back? Yeah that could be something, but I am not sure what unexpected consequences that could bring, as python 3 is by default using UTF-8 for strings, if suddlenly they are in other encodings, the user will have to manage all of that themselves ... which is an option if they know what they are doing ... 
I am intrigued to know if that would help in this particular case. I will test that quickly by converting the bytes to some windows friendlier encoding and see if that is displayed correctly.

**Comment by ofajardo** [comment]
Nope, switching to GBK still displays the squares with questionmarks. Windows-1252 does not even work. However apparently now on windows 10 the default encoding is UTF-8, so I think it makes sense to just stay on UTF-8

**Comment by evanmiller** [comment]
Correct, file_character_encoding overrides the input file's encoding, handler_character_encoding sets the returned encoding. Sticking with UTF-8 for Python 3 makes sense.

**Comment by ofajardo** [comment]
@jingyulong what do you get if you execute this code? does it look good? (screenshot if possible please)

```
g = b'\xc7\xeb\xcc\xe1\xb9\xa9\xbe\xa1\xbf\xc9\xc4\xdc\xb6\xe0\xb5\xc4\xb8\xbd\xbc\xd3\xcf\xb8\xbd\xda\xa1\xa3'
print(g.decode('GBK'))
```

**Comment by jingyulong** [comment]
> @jingyulong what do you get if you execute this code? does it look good? (screenshot if possible please)
> 
> ```
> g = b'\xc7\xeb\xcc\xe1\xb9\xa9\xbe\xa1\xbf\xc9\xc4\xdc\xb6\xe0\xb5\xc4\xb8\xbd\xbc\xd3\xcf\xb8\xbd\xda\xa1\xa3'
> print(g.decode('GBK'))
> ```

Sorry for the late reply. Regarding the character encoding problem you mentioned, there is no problem on my computer. It may be because the system of my computer is in the Chinese language environment.

With the code above, my execution result can be displayed correctly.

Regarding why I don’t use the default encoding when reading sav files, it’s because there are some sav files, the default UTF-8 reading will report the same exception prompt, and then there is no problem with the GBK encoding format. But I have a data file that can't be read in either way, so I'm trying to eliminate the problem. When I have time, I will find a clean environment and make another test data.
