### ISSUE TITLE
How to get Align and Role from SPSS DATA

### ISSUE THREAD

**Issue by datalover2020** [Roche/pyreadstat#86]
Hello :))

Im trying to get all the information in the picture below:
![bsp_spss](https://user-images.githubusercontent.com/74290950/98790419-fb076600-2403-11eb-9b05-ebccd7a16e46.png)

But i can not find the function for Align and Role?
Meta-function i did found: 
meta.column_names
meta.original_variable_types
meta.original_variable_types
meta.original_variable_types
meta.column_labels
meta.value_labels
meta.missing_user_values
meta.variable_display_width
meta.variable_measure
Is there somewhere and full overview over the meta functions or a guid to get all the values in the picture?

Sorry for the noobish question im super new to working with spss-data.

Much love for you work!

**Comment by ofajardo** [comment]
The overview of the meta class members is in the documentation: https://ofajardo.github.io/pyreadstat_documentation/_build/html/index.html

alignment should be meta.variable_alignment however it may be incorrect. 
Role is not retrieved at the moment. 

If you would like to get alignment and Role, please attach a sample file with a screenshot of what those values are in SPSS and what you are currently getting for variable_alignment.

**Comment by ofajardo** [comment]
closed due to inactivity and lack of reproducibility.
