### ISSUE TITLE
Not able to keep the true format/ encoding of "Restricted Numeric" type

### ISSUE THREAD

**Issue by datalover2020** [Roche/pyreadstat#93]
**Describe the issue**
Trying to read in an sav.-file and should not change the format/encoding of the data. So it would be possible to write the dataframe back to sav without any changes.
But while trying i lose leading zeros or trailing zeros:
how it is in the sav-file: 
![image](https://user-images.githubusercontent.com/74290950/101042417-77154980-357d-11eb-800e-144a9fe3318d.png)
how it is in df: 
![image](https://user-images.githubusercontent.com/74290950/101042515-92805480-357d-11eb-9dc7-ff884a07e442.png)

i thougt it should be something with encoding parameter, but had no luck with it.

To Reproduce
Steps to reproduce the behavior.
read in sav. file with leading zeros or trailing zeros.

File example
Please include an example file. If we are not able to reproduce the issue, we cannot fix it!

Expected behavior
Keep format like the sav.file

Setup Information:
How did you install pyreadstat? (pip, conda)
Platform (windows)
Python Version 3,7; 3,8
Python Distribution (System, plain python, Anaconda)
Using Virtualenv or condaenv? both

**Comment by ofajardo** [comment]
while you don't provide enough information to reproduce it (also no example file), most likely the C backend "Readstat" does not provide the options to set those formatting options and therefore it is not possible to do. You can open an issue over there to see if it can be implemented, you definitely have to provide a sample file. Also specify what is the format you are setting in spss and what are you getting as a format when reading in pyreadstat. 

You can at least set the formatting for the numbers to look as integers (no decimal points) by casting your pandas columns to integer, see [here](https://github.com/Roche/pyreadstat/issues/46). Regarding the zero-padding, no idea, as I said before Readstat does not provide options to directly control the formatting and also you are not saying what formatting is that (your report is not reproducible).

**Comment by ofajardo** [comment]
I have realized that actually it is possible to be implemented. It will be there for the next version.

**Comment by ofajardo** [comment]
implemented in version 1.0.7, you have now a new argument variable_format, you can set the restricted_integer format as:
variable_format={'Column_name':'restricted_integer'} or get the format directly from meta.original_variable_formats, 
see here: https://github.com/Roche/pyreadstat#setting-variable-formats
