### ISSUE TITLE
Writing Labels to .sav files

### ISSUE THREAD

**Issue by jttaggart** [Roche/pyreadstat#98]
Writing files to .sav does not write Label.
Value labels are written OK.

import pyreadstat

read_savFile = "sample.sav"
df, meta = pyreadstat.read_sav(read_savFile, user_missing=False)
pyreadstat.write_sav(df, "saved_1.sav")
pyreadstat.write_sav(df, "saved_2.sav", variable_value_labels=meta.variable_value_labels)

saved_1.sav has no Labels and no Value labels
saveed_2.sav has Value labels but no Labels

File example
Please include an example file. If we are not able to reproduce the issue, we cannot fix it!

Expected behavior
I woud have exoected saved_1.sav to have both Labels and Value labels
[sample.zip](https://github.com/Roche/pyreadstat/files/5716730/sample.zip)

Setup Information:
How did you install pyreadstat? (pip, conda, directly from repo)
PyCharm
Platform (windows, macOS, linux, 32 or 64 bit)
Window10 64 bit
Python Version
3.7
Python Distribution (System, plain python, Anaconda)
Using PyCharm
Using Virtualenv or condaenv?
Using MyCharm

**Comment by ofajardo** [comment]
You need to use the argument "column_labels"

```
pyreadstat.write_sav(df, "saved_3.sav", variable_value_labels=meta.variable_value_labels, column_labels=meta.column_labels)
```

For all possibilities, please check the documentation: Module documentation. Check the write_sav function documentation. The description of the metadata object at the beginning of the documentation will also help you.

**Comment by jttaggart** [comment]
Thank you so much.

 

I tried: meta.column_names_to_labels. Close but no cigar.

 

Oddly, enough I’ve been using pyreadstat for almost a year but this is the first time I had to write a .sav file. Normally, I’m writing scripts for other applications and writing text files for data.

 

And thank you again for pyreadstat.

 

If you’re ever in San Francisco, the drinks are on me.

**Comment by ofajardo** [comment]
yeah, as described in my answer it has to be meta.column_labels not any other variable. The function documentation for write_sav explains what variables are accepted, please read it carefully.
