### ISSUE TITLE
Certain characters appearing in strings trigger an error

### ISSUE THREAD

**Issue by ldulude** [Roche/pyreadstat#99]
Please read the README, particularly the known limitations section!

**Describe the issue**
When using pyreadstat to open a .sav file with certain non-Latin characters, a UnicodeDecodeError is triggered, which makes the file unreadable.

**To Reproduce**
`df, meta = pyreadstat.read_sav(dfloc, metadataonly=False)` using the attached file.

**File example**
[Example.zip](https://github.com/Roche/pyreadstat/files/5751019/Example.zip)

**Expected behavior**
I expected the file to open and be stored in df. If a unicode error occurred, I would expect the character to be replaced by some placeholder.

**Setup Information:**
_How did you install pyreadstat?_ pip
_Platform_ Windows, 64 bit
_Python Version_ 3.7.6
_Python Distribution_ Anaconda
_Using Virtualenv or condaenv?_ Jupyter Notebook

**Comment by ofajardo** [comment]
I cannot reproduce the error, this is what I get:

```
>>> import pyreadstat
>>> df, meta = pyreadstat.read_sav("Example.sav")
>>> df
                                              Q15ac1
0  企業でCCに加入しているという理由で、自社のAdobe担当者に問い合わせ内容をまとめて、Ad...
**
```

Please make sure you are using the last version of pyreadstat.

**Comment by ldulude** [comment]
I updated pyreadstat via conda and ran the code from the Anaconda command prompt; I'm still getting the same error:

`>>> df, meta = pyreadstat.read_sav(dfloc) 
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>
  File "pyreadstat\pyreadstat.pyx", line 325, in pyreadstat.pyreadstat.read_sav
  File "pyreadstat\_readstat_parser.pyx", line 945, in pyreadstat._readstat_parser.run_conversion
  File "pyreadstat\_readstat_parser.pyx", line 573, in pyreadstat._readstat_parser.handle_value
  File "pyreadstat\_readstat_parser.pyx", line 272, in pyreadstat._readstat_parser.convert_readstat_to_python_value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 511: unexpected end of data`

**Comment by ofajardo** [comment]
The error is coming from Line 272, pyreadstat._readstat_parser.convert_readstat_to_python_value. thats currently this:

https://github.com/Roche/pyreadstat/blob/master/pyreadstat/_readstat_parser.pyx#L272

While I would expect this error coming from L279.

However in old versions what now is L279 used to be L272. That for me suggests you are running an old version somehow.

Do print(pyreadstat.__file__) to see where it is and get rid of that old version.

**Comment by ofajardo** [comment]
Maybe you did pip install pyreadtat long ago and try to update with the same command? You need pip install pyreadtat --upgrade to force pip to install the new version. Or do pip uninstall pyreadtat to clean and reinstall

**Comment by ldulude** [comment]
You're right; I'm using conda for the Anaconda installation and missed that I needed "conda update" rather than "conda install"
